import 'dart:io';
import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

Future<int> _renderOne(pw.Font font) async {
  final doc = pw.Document();
  doc.addPage(pw.MultiPage(
    pageFormat: PdfPageFormat.a4,
    margin: const pw.EdgeInsets.fromLTRB(24, 28, 24, 40),
    build: (ctx) => [
      pw.Header(level: 0, child: pw.Text('PAYSLIP INVOICE - LONGER TITLE TO WIDEN LAYOUT')),
      pw.SizedBox(height: 8),
      pw.TableHelper.fromTextArray(
        headers: ['#','Name','Position','Days','Absents','Leaves','Overtime','Gross','Ded','Net'],
        data: [for (var r = 0; r < 12; r++) [r+1, 'Employee Name', 'Software Engineer', '30', '2', '1', '5000', '200000', '3000', '197000']],
        headerStyle: pw.TextStyle(font: pw.Font.helveticaBold(), fontSize: 8),
        cellStyle: pw.TextStyle(font: font, fontSize: 8),
        cellAlignment: pw.Alignment.centerLeft,
        border: pw.TableBorder.all(),
      ),
      pw.SizedBox(height: 10),
      pw.Container(height: 40, width: 120, alignment: pw.Alignment.center, decoration: pw.BoxDecoration(border: pw.Border.all(), color: PdfColors.red50),
        child: pw.Text('COMPANY STAMP', style: pw.TextStyle(font: font, fontSize: 8, color: PdfColors.red600))),
    ],
    footer: (ctx) => pw.Text('Generated by HRMS - Thank you', style: pw.TextStyle(font: font, fontSize: 8)),
  ));
  final bytes = await doc.save();
  return bytes.lengthInBytes;
}

Future<void> main() async {
  final fontBytes = File('/Users/macbookpro/hrms/assets/fonts/SF-Pro.ttf').readAsBytesSync();
  final swFont = Stopwatch()..start();
  final font = pw.Font.ttf(ByteData.sublistView(fontBytes));
  swFont.stop();
  print('FONT_PARSE: ${fontBytes.length} bytes parsed in ${swFont.elapsedMilliseconds}ms');
  await _renderOne(font);
  final n = 100;
  final sw = Stopwatch()..start();
  for (var i = 0; i < n; i++) { await _renderOne(font); }
  sw.stop();
  final perMs = sw.elapsedMilliseconds / n;
  print('PDF_BENCH: ' + n.toString() + ' sequential PDFs in ' + sw.elapsedMilliseconds.toString() + 'ms => ' + perMs.toStringAsFixed(1) + ' ms/PDF');
}
