name: hrms
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.11.5

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  firebase_core: ^4.10.0
  flutter_svg: ^2.3.0
  window_manager: ^0.5.1
  firebase_auth: ^6.5.2
  cloud_firestore: ^6.5.0
  shared_preferences: ^2.5.5
  fl_chart: ^0.70.2
  flutter_launcher_icons: ^0.14.4
  flashy_flushbar: ^1.4.1
  intl: ^0.20.2
  file_picker: ^11.0.2
  firebase_storage: ^13.4.2
  pdfx: ^2.9.0
  url_launcher: ^6.3.2
  google_sign_in: ^7.2.0
  sign_in_with_apple: ^6.1.1
  share_plus: ^12.0.2
  easy_localization: ^3.0.7
  csv: ^8.0.0
  path_provider: ^2.1.5
  open_file_plus: ^3.4.1+1
  cached_network_image: ^3.4.1
  provider: ^6.1.2
  flutter_inappwebview: ^6.1.5
  pdf: ^3.11.2
  image: ^4.8.0

flutter_launcher_icons:
  android: true
  ios: true
  macos:
   generate: true
  image_path: "assets/app_icon.png"



dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_core_platform_interface: ^7.0.1

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/translations/
    - assets/app_icon.svg
    - assets/splashscreenbg.png
    - assets/auth_bg.png
    - assets/premium_bg.png
    - assets/HR.svg
    - assets/HR_dark.svg
    # - assets/HR.svg

    - assets/langauge_icon.png
    - assets/dashbaord_icon_slidebar.svg
    - assets/workers_icon_slidebar.svg
    - assets/workforce_icon_sldiebar.svg
    - assets/expenses_icon_slidebar.svg
    - assets/settings_icon_slidebar.svg
    - assets/total_salary.svg
    - assets/total_expense.svg
    - assets/holidays_icon.svg
    - assets/payroll_icon.svg
    - assets/time_off_icon.svg
    - assets/left_arrow.png
    - assets/notification_icon.svg
    - assets/right_arrow_icon.svg
    - assets/tick_icon.svg
    - assets/premium_icon.png
    - assets/delete_icon.svg
    - assets/edit_icon.svg
    - assets/edit_pencil_profile.svg
    - assets/add_worker.svg
    - assets/add_bulk_worker.svg
    - assets/add_expense.svg
    - assets/add asset.svg
    - assets/assets_icon.svg
    - assets/company_email.svg
    - assets/company_id.svg
    - assets/cnic_back.svg
    - assets/cnic_front.svg
    - assets/currency_preview.svg
    - assets/location_preview.svg
    - assets/phone_preview.svg
    - assets/preview_profile.svg
    - assets/placeholder_workers.svg
    - "assets/search icon.svg"
    - assets/Upload_profile.svg
    - assets/profileimage.png
    - assets/profile_pic.png
    - assets/profile_placeholder.png
    - assets/expense_month.svg
    - assets/leave.svg
    - assets/leave_grey.svg
    - assets/absent.svg
    - assets/total_workers.svg
    - assets/email.svg
    - assets/email.png
    - assets/call.png

    - assets/present_grey.svg
    - assets/right_back_arrow.png
    - assets/changepassword.svg
    - assets/permenantly_delete.svg
    - assets/lanuguage.svg
    - assets/share.svg
    - assets/share1.svg
    - assets/terms&condition.svg
    - assets/privacy_policy.svg
    - assets/signout.svg
    - assets/boy.png
    - assets/placeholdemptystate.png
    - assets/sucess.png
    - assets/google_icon.svg
    - assets/apple_icon.svg
    - assets/guest_icon.svg
    - assets/expense.png
    - assets/expenses.png
    - assets/Present.png

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SFPRODISPLAYREGULAR.OTF
        - asset: assets/fonts/SFPRODISPLAYMEDIUM.OTF
          weight: 500
        - asset: assets/fonts/SFPRODISPLAYSEMIBOLDITALIC.OTF
          style: italic
          weight: 600
        - asset: assets/fonts/SFPRODISPLAYLIGHTITALIC.OTF
          style: italic
          weight: 300
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
