import 'dart:convert';
import 'package:shared_preferences/shared_preferences.dart';

class DummyData {
  static const _dataVersionKey = 'dummy_data_version';
  static const _currentDataVersion = 6;
  static Map<String, dynamic>? _sourceDefaults;

  static dynamic _clone(dynamic value) {
    if (value is Map) {
      return value.map((key, item) => MapEntry(key.toString(), _clone(item)));
    }
    if (value is List) {
      return value.map(_clone).toList();
    }
    return value;
  }

  static void _captureSourceDefaults() {
    _sourceDefaults ??= {
      'workers': _clone(workers),
      'expenses': _clone(expenses),
      'attendance': _clone(attendance),
      'payroll': _clone(payroll),
      'timeoff': _clone(timeoff),
      'holidays': _clone(holidays),
      'notifications': _clone(notifications),
      'assets': _clone(assets),
    };
  }

  
  static Future<void> resetToDefaults() async {
    _captureSourceDefaults();
    final defaults = _sourceDefaults!;

    workers
      ..clear()
      ..addAll(
        (defaults['workers'] as List).map(
          (item) => Map<String, dynamic>.from(_clone(item) as Map),
        ),
      );
    expenses
      ..clear()
      ..addAll(
        (defaults['expenses'] as List).map(
          (item) => Map<String, dynamic>.from(_clone(item) as Map),
        ),
      );
    attendance
      ..clear()
      ..addAll(
        (defaults['attendance'] as List).map(
          (item) => Map<String, dynamic>.from(_clone(item) as Map),
        ),
      );
    payroll
      ..clear()
      ..addAll(
        (defaults['payroll'] as List).map(
          (item) => Map<String, dynamic>.from(_clone(item) as Map),
        ),
      );
    timeoff
      ..clear()
      ..addAll(
        (defaults['timeoff'] as List).map(
          (item) => Map<String, dynamic>.from(_clone(item) as Map),
        ),
      );
    assets
      ..clear()
      ..addAll(
        (defaults['assets'] as List).map(
          (item) => Map<String, dynamic>.from(_clone(item) as Map),
        ),
      );
    notifications
      ..clear()
      ..addAll(
        (defaults['notifications'] as List).map(
          (item) => Map<String, dynamic>.from(_clone(item) as Map),
        ),
      );

    holidays.clear();
    final defaultHolidays = defaults['holidays'] as Map;
    for (final entry in defaultHolidays.entries) {
      holidays[entry.key.toString()] = (entry.value as List)
          .map((item) => Map<String, dynamic>.from(_clone(item) as Map))
          .toList();
    }

    await saveToPrefs();
  }

  static Future<void> loadFromPrefs() async {
    
    _captureSourceDefaults();
    final prefs = await SharedPreferences.getInstance();

    workers
      ..clear()
      ..addAll(_prefsList(prefs, 'workers'));
    expenses
      ..clear()
      ..addAll(_prefsList(prefs, 'expenses'));
    attendance
      ..clear()
      ..addAll(_prefsList(prefs, 'attendance'));
    payroll
      ..clear()
      ..addAll(_prefsList(prefs, 'payroll'));
    timeoff
      ..clear()
      ..addAll(_prefsList(prefs, 'timeoff'));
    assets
      ..clear()
      ..addAll(_prefsList(prefs, 'assets'));
    notifications
      ..clear()
      ..addAll(_prefsList(prefs, 'notifications'));

    final savedHolidaysJson = prefs.getString('holidays');
    if (savedHolidaysJson != null && savedHolidaysJson.isNotEmpty) {
      holidays.clear();
      final Map<String, dynamic> parsed = json.decode(savedHolidaysJson);
      for (final entry in parsed.entries) {
        final list = (entry.value as List)
            .map((item) => Map<String, dynamic>.from(item))
            .toList();
        holidays[entry.key.toString()] = list;
      }
    }
  }

  static Future<void> saveToPrefs() async {
    final prefs = await SharedPreferences.getInstance();

    await prefs.setString('workers', json.encode(workers));
    await prefs.setString('expenses', json.encode(expenses));
    await prefs.setString('attendance', json.encode(attendance));
    await prefs.setString('payroll', json.encode(payroll));
    await prefs.setString('timeoff', json.encode(timeoff));
    await prefs.setString('notifications', json.encode(notifications));
    await prefs.setString('holidays', json.encode(holidays));
    await prefs.setString('assets', json.encode(assets));
    await prefs.setInt(_dataVersionKey, _currentDataVersion);
  }

  static List<Map<String, dynamic>> _prefsList(
      SharedPreferences prefs, String key) {
    final jsonStr = prefs.getString(key);
    if (jsonStr == null || jsonStr.isEmpty) return [];
    try {
      final List<dynamic> list = json.decode(jsonStr);
      return list.map((e) => Map<String, dynamic>.from(e)).toList();
    } catch (_) {
      return [];
    }
  }

  static final List<Map<String, dynamic>> workers = [
    {
      'workerId': '0',
      'name': 'Michael Johnson',
      'position': 'DevOps Engineer',
      'workType': 'employee',
      'attendanceType': 'on_site',
      'experienceLevel': 'senior',
      'joiningDate': '01/10/2020',
      'fatherName': 'Robert Johnson',
      'email': 'michael.johnson@example.com',
      'contact': '+1 (555) 232-3232',
      'nationalId': '789-01-2345',
      'religion': 'Christian',
      'dob': '22/08/1988',
      'gender': 'male',
      'address': '789 Pine St, Boston, MA',
      'relationshipStatus': 'married',
      'education': 'master',
      'currency': 'USD',
      'salaryType': 'fixed',
      'salaryAmount': 95000,
      'leavePolicy': 'standard',
      'annualLeaves': 15,
      'sickLeaves': 10,
      'casualLeaves': 5,
      'profileImage': 'assets/boy.png',
      'cnicFrontUrl': null,
      'cnicBackUrl': null,
      'cvUrl': null,
    },
    {
      'workerId': '1',
      'name': 'Sophia Martinez',
      'position': 'HR Manager',
      'workType': 'employee',
      'attendanceType': 'on_site',
      'experienceLevel': 'senior',
      'joiningDate': '15/03/2021',
      'fatherName': 'Carlos Martinez',
      'email': 'sophia.martinez@example.com',
      'contact': '+1 (555) 343-4343',
      'nationalId': '890-12-3456',
      'religion': 'Christian',
      'dob': '05/07/1990',
      'gender': 'female',
      'address': '101 Pine St, Denver, CO',
      'relationshipStatus': 'married',
      'education': 'master',
      'currency': 'USD',
      'salaryType': 'fixed',
      'salaryAmount': 88000,
      'leavePolicy': 'standard',
      'annualLeaves': 15,
      'sickLeaves': 10,
      'casualLeaves': 5,
      'profileImage': 'assets/imageplaceholder.png',
      'cnicFrontUrl': null,
      'cnicBackUrl': null,
      'cvUrl': null,
    },
    {
      'workerId': '2',
      'name': 'Daniel Anderson',
      'position': 'Frontend Developer',
      'workType': 'employee',
      'attendanceType': 'remote',
      'experienceLevel': 'mid_level',
      'joiningDate': '10/06/2022',
      'fatherName': 'Mark Anderson',
      'email': 'daniel.anderson@example.com',
      'contact': '+1 (555) 454-5454',
      'nationalId': '901-23-4567',
      'religion': 'Christian',
      'dob': '12/11/1994',
      'gender': 'male',
      'address': '202 Cedar St, Austin, TX',
      'relationshipStatus': 'single',
      'education': 'bachelor',
      'currency': 'USD',
      'salaryType': 'fixed',
      'salaryAmount': 82000,
      'leavePolicy': 'standard',
      'annualLeaves': 15,
      'sickLeaves': 10,
      'casualLeaves': 5,
      'profileImage': 'assets/boy.png',
      'cnicFrontUrl': null,
      'cnicBackUrl': null,
      'cvUrl': null,
    },
    {
      'workerId': '3',
      'name': 'Olivia Thomas',
      'position': 'UI Designer',
      'workType': 'employee',
      'attendanceType': 'on_site',
      'experienceLevel': 'mid_level',
      'joiningDate': '05/09/2022',
      'fatherName': 'William Thomas',
      'email': 'olivia.thomas@example.com',
      'contact': '+1 (555) 565-6565',
      'nationalId': '012-34-5678',
      'religion': 'Christian',
      'dob': '28/02/1993',
      'gender': 'female',
      'address': '303 Maple St, Seattle, WA',
      'relationshipStatus': 'single',
      'education': 'bachelor',
      'currency': 'USD',
      'salaryType': 'fixed',
      'salaryAmount': 78000,
      'leavePolicy': 'standard',
      'annualLeaves': 15,
      'sickLeaves': 10,
      'casualLeaves': 5,
      'profileImage': 'assets/imageplaceholder.png',
      'cnicFrontUrl': null,
      'cnicBackUrl': null,
      'cvUrl': null,
    },
    {
      'workerId': '4',
      'name': 'James Miller',
      'position': 'Backend Engineer',
      'workType': 'employee',
      'attendanceType': 'remote',
      'experienceLevel': 'senior',
      'joiningDate': '20/01/2021',
      'fatherName': 'David Miller',
      'email': 'james.miller@example.com',
      'contact': '+1 (555) 676-7676',
      'nationalId': '123-45-6789',
      'religion': 'Christian',
      'dob': '15/06/1987',
      'gender': 'male',
      'address': '404 Birch St, San Francisco, CA',
      'relationshipStatus': 'married',
      'education': 'master',
      'currency': 'USD',
      'salaryType': 'fixed',
      'salaryAmount': 110000,
      'leavePolicy': 'standard',
      'annualLeaves': 15,
      'sickLeaves': 10,
      'casualLeaves': 5,
      'profileImage': 'assets/boy.png',
      'cnicFrontUrl': null,
      'cnicBackUrl': null,
      'cvUrl': null,
    },
    {
      'workerId': '5',
      'name': 'Emily Davis',
      'position': 'Data Analyst',
      'workType': 'employee',
      'attendanceType': 'on_site',
      'experienceLevel': 'junior',
      'joiningDate': '12/03/2023',
      'fatherName': 'John Davis',
      'email': 'emily.davis@example.com',
      'contact': '+1 (555) 787-8787',
      'nationalId': '234-56-7890',
      'religion': 'Christian',
      'dob': '08/09/1998',
      'gender': 'female',
      'address': '505 Oak St, Chicago, IL',
      'relationshipStatus': 'single',
      'education': 'bachelor',
      'currency': 'USD',
      'salaryType': 'fixed',
      'salaryAmount': 65000,
      'leavePolicy': 'standard',
      'annualLeaves': 15,
      'sickLeaves': 10,
      'casualLeaves': 5,
      'profileImage': 'assets/imageplaceholder.png',
      'cnicFrontUrl': null,
      'cnicBackUrl': null,
      'cvUrl': null,
    },
    {
      'workerId': '6',
      'name': 'William Brown',
      'position': 'Product Manager',
      'workType': 'employee',
      'attendanceType': 'hybrid',
      'experienceLevel': 'senior',
      'joiningDate': '08/09/2019',
      'fatherName': 'Richard Brown',
      'email': 'william.brown@example.com',
      'contact': '+1 (555) 898-9898',
      'nationalId': '345-67-8901',
      'religion': 'Christian',
      'dob': '03/04/1986',
      'gender': 'male',
      'address': '606 Walnut St, New York, NY',
      'relationshipStatus': 'married',
      'education': 'master',
      'currency': 'USD',
      'salaryType': 'fixed',
      'salaryAmount': 120000,
      'leavePolicy': 'standard',
      'annualLeaves': 15,
      'sickLeaves': 10,
      'casualLeaves': 5,
      'profileImage': 'assets/boy.png',
      'cnicFrontUrl': null,
      'cnicBackUrl': null,
      'cvUrl': null,
    },
    {
      'workerId': '7',
      'name': 'Amelia White',
      'position': 'Graphic Designer',
      'workType': 'employee',
      'attendanceType': 'on_site',
      'experienceLevel': 'junior',
      'joiningDate': '01/11/2023',
      'fatherName': 'Thomas White',
      'email': 'amelia.white@example.com',
      'contact': '+1 (555) 909-0909',
      'nationalId': '456-78-9012',
      'religion': 'Christian',
      'dob': '17/12/1997',
      'gender': 'female',
      'address': '707 Ash St, Portland, OR',
      'relationshipStatus': 'single',
      'education': 'bachelor',
      'currency': 'USD',
      'salaryType': 'fixed',
      'salaryAmount': 62000,
      'leavePolicy': 'standard',
      'annualLeaves': 15,
      'sickLeaves': 10,
      'casualLeaves': 5,
      'profileImage': 'assets/imageplaceholder.png',
      'cnicFrontUrl': null,
      'cnicBackUrl': null,
      'cvUrl': null,
    },
    {
      'workerId': '8',
      'name': 'Charlotte Martin',
      'position': 'Cyber Security Analyst',
      'workType': 'employee',
      'attendanceType': 'on_site',
      'experienceLevel': 'mid_level',
      'joiningDate': '20/05/2022',
      'fatherName': 'James Martin',
      'email': 'charlotte.martin@example.com',
      'contact': '+1 (555) 111-1112',
      'nationalId': '567-89-0123',
      'religion': 'Christian',
      'dob': '14/05/1992',
      'gender': 'female',
      'address': '808 Elm St, Miami, FL',
      'relationshipStatus': 'married',
      'education': 'master',
      'currency': 'USD',
      'salaryType': 'fixed',
      'salaryAmount': 95000,
      'leavePolicy': 'standard',
      'annualLeaves': 15,
      'sickLeaves': 10,
      'casualLeaves': 5,
      'profileImage': 'assets/boy.png',
      'cnicFrontUrl': null,
      'cnicBackUrl': null,
      'cvUrl': null,
    },
    {
      'workerId': '9',
      'name': 'Harper Garcia',
      'position': 'Technical Writer',
      'workType': 'employee',
      'attendanceType': 'remote',
      'experienceLevel': 'mid_level',
      'joiningDate': '15/08/2022',
      'fatherName': 'Luis Garcia',
      'email': 'harper.garcia@example.com',
      'contact': '+1 (555) 222-3233',
      'nationalId': '678-90-1234',
      'religion': 'Christian',
      'dob': '09/03/1995',
      'gender': 'female',
      'address': '909 Pine St, Atlanta, GA',
      'relationshipStatus': 'single',
      'education': 'bachelor',
      'currency': 'USD',
      'salaryType': 'fixed',
      'salaryAmount': 72000,
      'leavePolicy': 'standard',
      'annualLeaves': 15,
      'sickLeaves': 10,
      'casualLeaves': 5,
      'profileImage': 'assets/imageplaceholder.png',
      'cnicFrontUrl': null,
      'cnicBackUrl': null,
      'cvUrl': null,
    },
    {
      'workerId': '10',
      'name': 'Benjamin Harris',
      'position': 'Mobile Developer',
      'workType': 'employee',
      'attendanceType': 'hybrid',
      'experienceLevel': 'mid_level',
      'joiningDate': '10/04/2023',
      'fatherName': 'Christopher Harris',
      'email': 'benjamin.harris@example.com',
      'contact': '+1 (555) 333-4344',
      'nationalId': '789-01-2346',
      'religion': 'Christian',
      'dob': '25/08/1993',
      'gender': 'male',
      'address': '111 Cedar St, Dallas, TX',
      'relationshipStatus': 'single',
      'education': 'bachelor',
      'currency': 'USD',
      'salaryType': 'fixed',
      'salaryAmount': 85000,
      'leavePolicy': 'standard',
      'annualLeaves': 15,
      'sickLeaves': 10,
      'casualLeaves': 5,
      'profileImage': 'assets/boy.png',
      'cnicFrontUrl': null,
      'cnicBackUrl': null,
      'cvUrl': null,
    },
    {
      'workerId': '11',
      'name': 'Lucas Taylor',
      'position': 'Solutions Architect',
      'workType': 'employee',
      'attendanceType': 'hybrid',
      'experienceLevel': 'senior',
      'joiningDate': '05/12/2019',
      'fatherName': 'Andrew Taylor',
      'email': 'lucas.taylor@example.com',
      'contact': '+1 (555) 444-5455',
      'nationalId': '890-12-3457',
      'religion': 'Christian',
      'dob': '18/11/1985',
      'gender': 'male',
      'address': '222 Birch St, Phoenix, AZ',
      'relationshipStatus': 'married',
      'education': 'master',
      'currency': 'USD',
      'salaryType': 'fixed',
      'salaryAmount': 135000,
      'leavePolicy': 'standard',
      'annualLeaves': 15,
      'sickLeaves': 10,
      'casualLeaves': 5,
      'profileImage': 'assets/imageplaceholder.png',
      'cnicFrontUrl': null,
      'cnicBackUrl': null,
      'cvUrl': null,
    },
    {
      'workerId': '12',
      'name': 'Ethan Clark',
      'position': 'QA Engineer',
      'workType': 'employee',
      'attendanceType': 'on_site',
      'experienceLevel': 'mid_level',
      'joiningDate': '18/07/2022',
      'fatherName': 'Michael Clark',
      'email': 'ethan.clark@example.com',
      'contact': '+1 (555) 555-6566',
      'nationalId': '901-23-4568',
      'religion': 'Christian',
      'dob': '30/10/1992',
      'gender': 'male',
      'address': '333 Elm St, Minneapolis, MN',
      'relationshipStatus': 'single',
      'education': 'bachelor',
      'currency': 'USD',
      'salaryType': 'fixed',
      'salaryAmount': 75000,
      'leavePolicy': 'standard',
      'annualLeaves': 15,
      'sickLeaves': 10,
      'casualLeaves': 5,
      'profileImage': 'assets/boy.png',
      'cnicFrontUrl': null,
      'cnicBackUrl': null,
      'cvUrl': null,
    },
    {
      'workerId': '13',
      'name': 'Mia Robinson',
      'position': 'Content Strategist',
      'workType': 'employee',
      'attendanceType': 'remote',
      'experienceLevel': 'junior',
      'joiningDate': '22/01/2024',
      'fatherName': 'Daniel Robinson',
      'email': 'mia.robinson@example.com',
      'contact': '+1 (555) 666-7677',
      'nationalId': '012-34-5679',
      'religion': 'Christian',
      'dob': '07/04/1999',
      'gender': 'female',
      'address': '444 Oak St, San Diego, CA',
      'relationshipStatus': 'single',
      'education': 'bachelor',
      'currency': 'USD',
      'salaryType': 'fixed',
      'salaryAmount': 58000,
      'leavePolicy': 'standard',
      'annualLeaves': 15,
      'sickLeaves': 10,
      'casualLeaves': 5,
      'profileImage': 'assets/imageplaceholder.png',
      'cnicFrontUrl': null,
      'cnicBackUrl': null,
      'cvUrl': null,
    },
    {
      'workerId': '14',
      'name': 'Alexander Lee',
      'position': 'Cloud Architect',
      'workType': 'employee',
      'attendanceType': 'remote',
      'experienceLevel': 'senior',
      'joiningDate': '14/06/2020',
      'fatherName': 'Kevin Lee',
      'email': 'alexander.lee@example.com',
      'contact': '+1 (555) 777-8788',
      'nationalId': '123-45-6780',
      'religion': 'Christian',
      'dob': '02/09/1984',
      'gender': 'male',
      'address': '555 Maple Ave, Denver, CO',
      'relationshipStatus': 'married',
      'education': 'master',
      'currency': 'USD',
      'salaryType': 'fixed',
      'salaryAmount': 140000,
      'leavePolicy': 'standard',
      'annualLeaves': 15,
      'sickLeaves': 10,
      'casualLeaves': 5,
      'profileImage': 'assets/boy.png',
      'cnicFrontUrl': null,
      'cnicBackUrl': null,
      'cvUrl': null,
    },
    {
      'workerId': '15',
      'name': 'Isabella Walker',
      'position': 'UX Researcher',
      'workType': 'employee',
      'attendanceType': 'hybrid',
      'experienceLevel': 'mid_level',
      'joiningDate': '30/11/2022',
      'fatherName': 'Robert Walker',
      'email': 'isabella.walker@example.com',
      'contact': '+1 (555) 888-9899',
      'nationalId': '234-56-7891',
      'religion': 'Christian',
      'dob': '19/01/1994',
      'gender': 'female',
      'address': '666 Walnut St, Nashville, TN',
      'relationshipStatus': 'single',
      'education': 'bachelor',
      'currency': 'USD',
      'salaryType': 'fixed',
      'salaryAmount': 80000,
      'leavePolicy': 'standard',
      'annualLeaves': 15,
      'sickLeaves': 10,
      'casualLeaves': 5,
      'profileImage': 'assets/imageplaceholder.png',
      'cnicFrontUrl': null,
      'cnicBackUrl': null,
      'cvUrl': null,
    },
    {
      'workerId': '16',
      'name': 'John Smith',
      'position': 'Senior Web Developer',
      'workType': 'employee',
      'attendanceType': 'on_site',
      'experienceLevel': 'senior',
      'joiningDate': '15/03/2021',
      'fatherName': 'David Smith',
      'email': 'john.smith@company.com',
      'contact': '+1 (555) 0101',
      'nationalId': '456-78-9013',
      'religion': 'Christian',
      'dob': '12/06/1988',
      'gender': 'male',
      'address': '123 Main St, San Francisco, CA',
      'relationshipStatus': 'married',
      'education': 'master',
      'currency': 'USD',
      'salaryType': 'fixed',
      'salaryAmount': 95000,
      'leavePolicy': 'standard',
      'annualLeaves': 15,
      'sickLeaves': 10,
      'casualLeaves': 5,
      'profileImage': 'assets/boy.png',
      'cnicFrontUrl': null,
      'cnicBackUrl': null,
      'cvUrl': null,
    },
    {
      'workerId': '17',
      'name': 'Noah Wilson',
      'position': 'DevOps Lead',
      'workType': 'employee',
      'attendanceType': 'on_site',
      'experienceLevel': 'senior',
      'joiningDate': '01/03/2020',
      'fatherName': 'Robert Wilson',
      'email': 'noah.wilson@example.com',
      'contact': '+1 (555) 999-0900',
      'nationalId': '345-67-8902',
      'religion': 'Christian',
      'dob': '14/03/1985',
      'gender': 'male',
      'address': '777 Hickory St, Philadelphia, PA',
      'relationshipStatus': 'married',
      'education': 'master',
      'currency': 'USD',
      'salaryType': 'fixed',
      'salaryAmount': 125000,
      'leavePolicy': 'standard',
      'annualLeaves': 15,
      'sickLeaves': 10,
      'casualLeaves': 5,
      'profileImage': 'assets/imageplaceholder.png',
      'cnicFrontUrl': null,
      'cnicBackUrl': null,
      'cvUrl': null,
    },
    {
      'workerId': '18',
      'name': 'Ava Turner',
      'position': 'Marketing Lead',
      'workType': 'employee',
      'attendanceType': 'hybrid',
      'experienceLevel': 'senior',
      'joiningDate': '10/10/2020',
      'fatherName': 'George Turner',
      'email': 'ava.turner@example.com',
      'contact': '+1 (555) 000-1112',
      'nationalId': '456-78-9014',
      'religion': 'Christian',
      'dob': '27/08/1986',
      'gender': 'female',
      'address': '888 Willow St, Charlotte, NC',
      'relationshipStatus': 'married',
      'education': 'master',
      'currency': 'USD',
      'salaryType': 'fixed',
      'salaryAmount': 105000,
      'leavePolicy': 'standard',
      'annualLeaves': 15,
      'sickLeaves': 10,
      'casualLeaves': 5,
      'profileImage': 'assets/boy.png',
      'cnicFrontUrl': null,
      'cnicBackUrl': null,
      'cvUrl': null,
    },
    {
      'workerId': '19',
      'name': 'Emma Wilson',
      'position': 'Junior Developer',
      'workType': 'employee',
      'attendanceType': 'on_site',
      'experienceLevel': 'fresher',
      'joiningDate': '01/02/2024',
      'fatherName': 'James Wilson',
      'email': 'emma.wilson@example.com',
      'contact': '+1 (555) 111-2223',
      'nationalId': '567-89-0124',
      'religion': 'Christian',
      'dob': '11/11/2000',
      'gender': 'female',
      'address': '999 Ash St, Detroit, MI',
      'relationshipStatus': 'single',
      'education': 'bachelor',
      'currency': 'USD',
      'salaryType': 'fixed',
      'salaryAmount': 55000,
      'leavePolicy': 'standard',
      'annualLeaves': 15,
      'sickLeaves': 10,
      'casualLeaves': 5,
      'profileImage': 'assets/imageplaceholder.png',
      'cnicFrontUrl': null,
      'cnicBackUrl': null,
      'cvUrl': null,
    },
    
    {
      'workerId': '20',
      'name': 'Jordan Casey',
      'position': 'IT Support Specialist',
      'workType': 'employee',
      'attendanceType': 'on_site',
      'experienceLevel': 'mid_level',
      'joiningDate': '10/03/2023',
      'fatherName': 'Pat Casey',
      'email': 'jordan.casey@example.com',
      'contact': '+1 (555) 777-0001',
      'nationalId': '111-22-3333',
      'religion': 'Christian',
      'dob': '14/07/1993',
      'gender': 'other',
      'address': '100 Tech Blvd, Austin, TX',
      'relationshipStatus': 'single',
      'education': 'bachelor',
      'currency': 'USD',
      'salaryType': 'fixed',
      'salaryAmount': 62000,
      'leavePolicy': 'standard',
      'annualLeaves': 15,
      'sickLeaves': 10,
      'casualLeaves': 5,
      'profileImage': null,
      'cnicFrontUrl': null,
      'cnicBackUrl': null,
      'cvUrl': null,
    },
    {
      'workerId': '21',
      'name': 'Riley Morgan',
      'position': 'Business Analyst',
      'workType': 'employee',
      'attendanceType': 'hybrid',
      'experienceLevel': 'senior',
      'joiningDate': '05/06/2021',
      'fatherName': 'Sam Morgan',
      'email': 'riley.morgan@example.com',
      'contact': '+1 (555) 777-0002',
      'nationalId': '222-33-4444',
      'religion': 'None',
      'dob': '28/11/1989',
      'gender': 'other',
      'address': '200 Data Dr, Seattle, WA',
      'relationshipStatus': 'married',
      'education': 'master',
      'currency': 'USD',
      'salaryType': 'fixed',
      'salaryAmount': 92000,
      'leavePolicy': 'standard',
      'annualLeaves': 15,
      'sickLeaves': 10,
      'casualLeaves': 5,
      'profileImage': null,
      'cnicFrontUrl': null,
      'cnicBackUrl': null,
      'cvUrl': null,
    },
    {
      'workerId': '22',
      'name': 'Avery Quinn',
      'position': 'Event Coordinator',
      'workType': 'employee',
      'attendanceType': 'on_site',
      'experienceLevel': 'junior',
      'joiningDate': '20/01/2024',
      'fatherName': 'Drew Quinn',
      'email': 'avery.quinn@example.com',
      'contact': '+1 (555) 777-0003',
      'nationalId': '333-44-5555',
      'religion': 'Christian',
      'dob': '03/05/1998',
      'gender': 'other',
      'address': '300 Event Ln, Portland, OR',
      'relationshipStatus': 'single',
      'education': 'bachelor',
      'currency': 'USD',
      'salaryType': 'fixed',
      'salaryAmount': 52000,
      'leavePolicy': 'standard',
      'annualLeaves': 15,
      'sickLeaves': 10,
      'casualLeaves': 5,
      'profileImage': null,
      'cnicFrontUrl': null,
      'cnicBackUrl': null,
      'cvUrl': null,
    },
    {
      'workerId': '23',
      'name': 'Logan Reed',
      'position': 'System Administrator',
      'workType': 'employee',
      'attendanceType': 'remote',
      'experienceLevel': 'senior',
      'joiningDate': '12/04/2020',
      'fatherName': 'Terry Reed',
      'email': 'logan.reed@example.com',
      'contact': '+1 (555) 777-0004',
      'nationalId': '444-55-6666',
      'religion': 'Christian',
      'dob': '19/09/1986',
      'gender': 'male',
      'address': '400 SysAdmin Rd, Denver, CO',
      'relationshipStatus': 'married',
      'education': 'bachelor',
      'currency': 'USD',
      'salaryType': 'fixed',
      'salaryAmount': 105000,
      'leavePolicy': 'standard',
      'annualLeaves': 15,
      'sickLeaves': 10,
      'casualLeaves': 5,
      'profileImage': null,
      'cnicFrontUrl': null,
      'cnicBackUrl': null,
      'cvUrl': null,
    },
    {
      'workerId': '24',
      'name': 'Taylor Blake',
      'position': 'Social Media Manager',
      'workType': 'employee',
      'attendanceType': 'remote',
      'experienceLevel': 'mid_level',
      'joiningDate': '15/08/2022',
      'fatherName': 'Morgan Blake',
      'email': 'taylor.blake@example.com',
      'contact': '+1 (555) 777-0005',
      'nationalId': '555-66-7777',
      'religion': 'None',
      'dob': '07/03/1995',
      'gender': 'other',
      'address': '500 Social St, Los Angeles, CA',
      'relationshipStatus': 'single',
      'education': 'bachelor',
      'currency': 'USD',
      'salaryType': 'fixed',
      'salaryAmount': 68000,
      'leavePolicy': 'standard',
      'annualLeaves': 15,
      'sickLeaves': 10,
      'casualLeaves': 5,
      'profileImage': null,
      'cnicFrontUrl': null,
      'cnicBackUrl': null,
      'cvUrl': null,
    },
    {
      'workerId': '25',
      'name': 'Skyler Park',
      'position': 'Graphic Designer',
      'workType': 'employee',
      'attendanceType': 'hybrid',
      'experienceLevel': 'junior',
      'joiningDate': '01/11/2023',
      'fatherName': 'Jamie Park',
      'email': 'skyler.park@example.com',
      'contact': '+1 (555) 777-0006',
      'nationalId': '666-77-8888',
      'religion': 'Christian',
      'dob': '22/12/1999',
      'gender': 'other',
      'address': '600 Design Ave, San Francisco, CA',
      'relationshipStatus': 'single',
      'education': 'bachelor',
      'currency': 'USD',
      'salaryType': 'fixed',
      'salaryAmount': 56000,
      'leavePolicy': 'standard',
      'annualLeaves': 15,
      'sickLeaves': 10,
      'casualLeaves': 5,
      'profileImage': null,
      'cnicFrontUrl': null,
      'cnicBackUrl': null,
      'cvUrl': null,
    },
    {
      'workerId': '26',
      'name': 'Dakota Lee',
      'position': 'Data Engineer',
      'workType': 'employee',
      'attendanceType': 'remote',
      'experienceLevel': 'mid_level',
      'joiningDate': '18/05/2022',
      'fatherName': 'Alex Lee',
      'email': 'dakota.lee@example.com',
      'contact': '+1 (555) 777-0007',
      'nationalId': '777-88-9999',
      'religion': 'Christian',
      'dob': '10/10/1993',
      'gender': 'other',
      'address': '700 Data Ln, Chicago, IL',
      'relationshipStatus': 'single',
      'education': 'master',
      'currency': 'USD',
      'salaryType': 'fixed',
      'salaryAmount': 88000,
      'leavePolicy': 'standard',
      'annualLeaves': 15,
      'sickLeaves': 10,
      'casualLeaves': 5,
      'profileImage': null,
      'cnicFrontUrl': null,
      'cnicBackUrl': null,
      'cvUrl': null,
    },
    {
      'workerId': '27',
      'name': 'Casey Jones',
      'position': 'Office Manager',
      'workType': 'employee',
      'attendanceType': 'on_site',
      'experienceLevel': 'senior',
      'joiningDate': '08/02/2019',
      'fatherName': 'Robin Jones',
      'email': 'casey.jones@example.com',
      'contact': '+1 (555) 777-0008',
      'nationalId': '888-99-0000',
      'religion': 'Christian',
      'dob': '15/04/1985',
      'gender': 'other',
      'address': '800 Manager Ct, Miami, FL',
      'relationshipStatus': 'married',
      'education': 'bachelor',
      'currency': 'USD',
      'salaryType': 'fixed',
      'salaryAmount': 75000,
      'leavePolicy': 'standard',
      'annualLeaves': 15,
      'sickLeaves': 10,
      'casualLeaves': 5,
      'profileImage': null,
      'cnicFrontUrl': null,
      'cnicBackUrl': null,
      'cvUrl': null,
    },
    {
      'workerId': '28',
      'name': 'Finley Hart',
      'position': 'Junior QA Tester',
      'workType': 'employee',
      'attendanceType': 'on_site',
      'experienceLevel': 'fresher',
      'joiningDate': '05/06/2024',
      'fatherName': 'Gray Hart',
      'email': 'finley.hart@example.com',
      'contact': '+1 (555) 777-0009',
      'nationalId': '999-00-1111',
      'religion': 'None',
      'dob': '30/08/2000',
      'gender': 'other',
      'address': '900 Test Blvd, Dallas, TX',
      'relationshipStatus': 'single',
      'education': 'associate',
      'currency': 'USD',
      'salaryType': 'fixed',
      'salaryAmount': 45000,
      'leavePolicy': 'standard',
      'annualLeaves': 15,
      'sickLeaves': 10,
      'casualLeaves': 5,
      'profileImage': null,
      'cnicFrontUrl': null,
      'cnicBackUrl': null,
      'cvUrl': null,
    },
    {
      'workerId': '29',
      'name': 'Sage Winters',
      'position': 'Content Writer',
      'workType': 'employee',
      'attendanceType': 'remote',
      'experienceLevel': 'junior',
      'joiningDate': '20/02/2024',
      'fatherName': 'Rowan Winters',
      'email': 'sage.winters@example.com',
      'contact': '+1 (555) 777-0010',
      'nationalId': '000-11-2222',
      'religion': 'Christian',
      'dob': '12/04/1997',
      'gender': 'other',
      'address': '1000 Write St, Boston, MA',
      'relationshipStatus': 'single',
      'education': 'bachelor',
      'currency': 'USD',
      'salaryType': 'fixed',
      'salaryAmount': 50000,
      'leavePolicy': 'standard',
      'annualLeaves': 15,
      'sickLeaves': 10,
      'casualLeaves': 5,
      'profileImage': null,
      'cnicFrontUrl': null,
      'cnicBackUrl': null,
      'cvUrl': null,
    },
  ];

  static final List<Map<String, dynamic>> expenses = [
    
    {
      'name': 'Office Supplies',
      'category': 'Stationery',
      'amount': 250.0,
      'createdAt': '15/01/2026',
    },
    {
      'name': 'Team Lunch - Q1 Planning',
      'category': 'Food & Beverage',
      'amount': 475.0,
      'createdAt': '12/01/2026',
    },
    {
      'name': 'Cloud Server - January',
      'category': 'Software & IT',
      'amount': 1200.0,
      'createdAt': '10/01/2026',
    },
    {
      'name': 'Office Rent - January',
      'category': 'Rent',
      'amount': 5000.0,
      'createdAt': '05/01/2026',
    },
    {
      'name': 'New Year Decorations',
      'category': 'Entertainment',
      'amount': 180.0,
      'createdAt': '02/01/2026',
    },
    
    {
      'name': 'Employee Training: Flutter',
      'category': 'Training & Development',
      'amount': 850.0,
      'createdAt': '08/02/2026',
    },
    {
      'name': 'Internet & Phone Bills',
      'category': 'Utilities',
      'amount': 320.0,
      'createdAt': '03/02/2026',
    },
    {
      'name': 'Office Rent - February',
      'category': 'Rent',
      'amount': 5000.0,
      'createdAt': '05/02/2026',
    },
    {
      'name': 'Cloud Server - February',
      'category': 'Software & IT',
      'amount': 1200.0,
      'createdAt': '12/02/2026',
    },
    
    {
      'name': 'Cloud Server - March',
      'category': 'Software & IT',
      'amount': 1200.0,
      'createdAt': '10/03/2026',
    },
    {
      'name': 'Office Rent - March',
      'category': 'Rent',
      'amount': 5000.0,
      'createdAt': '05/03/2026',
    },
    {
      'name': 'Internet & Phone Bills',
      'category': 'Utilities',
      'amount': 320.0,
      'createdAt': '03/03/2026',
    },
    {
      'name': 'Team Building Activity',
      'category': 'Food & Beverage',
      'amount': 890.0,
      'createdAt': '20/03/2026',
    },
    
    {
      'name': 'Team Outing',
      'category': 'Food & Beverage',
      'amount': 680.0,
      'createdAt': '12/04/2026',
    },
    {
      'name': 'New Office Chairs',
      'category': 'Furniture',
      'amount': 2400.0,
      'createdAt': '20/04/2026',
    },
    {
      'name': 'Cloud Server - April',
      'category': 'Software & IT',
      'amount': 1200.0,
      'createdAt': '10/04/2026',
    },
    {
      'name': 'Office Rent - April',
      'category': 'Rent',
      'amount': 5000.0,
      'createdAt': '05/04/2026',
    },
    
    {
      'name': 'Internet & Phone Bills',
      'category': 'Utilities',
      'amount': 320.0,
      'createdAt': '03/05/2026',
    },
    {
      'name': 'Cloud Server - May',
      'category': 'Software & IT',
      'amount': 1200.0,
      'createdAt': '10/05/2026',
    },
    {
      'name': 'Office Rent - May',
      'category': 'Rent',
      'amount': 5000.0,
      'createdAt': '05/05/2026',
    },
    {
      'name': 'Annual Software Licenses',
      'category': 'Software & IT',
      'amount': 3500.0,
      'createdAt': '15/05/2026',
    },
    
    {
      'name': 'Office Rent - June',
      'category': 'Rent',
      'amount': 5000.0,
      'createdAt': '05/06/2026',
    },
    {
      'name': 'Employee Training: Leadership',
      'category': 'Training & Development',
      'amount': 1200.0,
      'createdAt': '08/06/2026',
    },
    {
      'name': 'Client Dinner',
      'category': 'Entertainment',
      'amount': 340.0,
      'createdAt': '22/06/2026',
    },
    {
      'name': 'Cloud Server - June',
      'category': 'Software & IT',
      'amount': 1200.0,
      'createdAt': '10/06/2026',
    },
    
    {
      'name': 'Freelance Graphic Design',
      'category': 'Professional Services',
      'amount': 600.0,
      'createdAt': '10/07/2026',
    },
    {
      'name': 'Office Rent - July',
      'category': 'Rent',
      'amount': 5000.0,
      'createdAt': '05/07/2026',
    },
    {
      'name': 'Cloud Server - July',
      'category': 'Software & IT',
      'amount': 1200.0,
      'createdAt': '12/07/2026',
    },
    {
      'name': 'Internet & Phone Bills',
      'category': 'Utilities',
      'amount': 320.0,
      'createdAt': '03/07/2026',
    },
    
    {
      'name': 'Office Rent - August',
      'category': 'Rent',
      'amount': 5000.0,
      'createdAt': '05/08/2026',
    },
    {
      'name': 'Cloud Server - August',
      'category': 'Software & IT',
      'amount': 1200.0,
      'createdAt': '10/08/2026',
    },
    {
      'name': 'Internet & Phone Bills',
      'category': 'Utilities',
      'amount': 320.0,
      'createdAt': '03/08/2026',
    },
    {
      'name': 'Office Supplies Restock',
      'category': 'Stationery',
      'amount': 450.0,
      'createdAt': '18/08/2026',
    },
    
    {
      'name': 'Cloud Server - September',
      'category': 'Software & IT',
      'amount': 1200.0,
      'createdAt': '10/09/2026',
    },
    {
      'name': 'Office Rent - September',
      'category': 'Rent',
      'amount': 5000.0,
      'createdAt': '05/09/2026',
    },
    {
      'name': 'Internet & Phone Bills',
      'category': 'Utilities',
      'amount': 320.0,
      'createdAt': '03/09/2026',
    },
    {
      'name': 'Employee Wellness Program',
      'category': 'Training & Development',
      'amount': 750.0,
      'createdAt': '22/09/2026',
    },
    
    {
      'name': 'Team Lunch - Q4 Planning',
      'category': 'Food & Beverage',
      'amount': 550.0,
      'createdAt': '12/10/2026',
    },
    {
      'name': 'Office Rent - October',
      'category': 'Rent',
      'amount': 5000.0,
      'createdAt': '05/10/2026',
    },
    {
      'name': 'Cloud Server - October',
      'category': 'Software & IT',
      'amount': 1200.0,
      'createdAt': '10/10/2026',
    },
    {
      'name': 'Halloween Office Decor',
      'category': 'Entertainment',
      'amount': 200.0,
      'createdAt': '28/10/2026',
    },
    
    {
      'name': 'Internet & Phone Bills',
      'category': 'Utilities',
      'amount': 320.0,
      'createdAt': '03/11/2026',
    },
    {
      'name': 'Cloud Server - November',
      'category': 'Software & IT',
      'amount': 1200.0,
      'createdAt': '10/11/2026',
    },
    {
      'name': 'Office Rent - November',
      'category': 'Rent',
      'amount': 5000.0,
      'createdAt': '05/11/2026',
    },
    {
      'name': 'Thanksgiving Team Dinner',
      'category': 'Food & Beverage',
      'amount': 620.0,
      'createdAt': '25/11/2026',
    },
    
    {
      'name': 'Year-end Party',
      'category': 'Entertainment',
      'amount': 1500.0,
      'createdAt': '15/12/2026',
    },
    {
      'name': 'Cloud Server - December',
      'category': 'Software & IT',
      'amount': 1200.0,
      'createdAt': '10/12/2026',
    },
    {
      'name': 'Office Rent - December',
      'category': 'Rent',
      'amount': 5000.0,
      'createdAt': '05/12/2026',
    },
    {
      'name': 'Christmas Gift Baskets',
      'category': 'Entertainment',
      'amount': 850.0,
      'createdAt': '18/12/2026',
    },
  ];

  static String _guestAttendanceDate(int daysAgo) {
    final date = DateTime.now().subtract(Duration(days: daysAgo));
    final day = date.day.toString().padLeft(2, '0');
    final month = date.month.toString().padLeft(2, '0');
    return '$day/$month/${date.year}';
  }

  static Map<String, dynamic> _guestAttendanceRecord(
    int workerIndex,
    int daysAgo,
  ) {
    const statuses = ['Present', 'Present', 'Present', 'Absent', 'Leave'];
    const absentReasons = ['Sick', 'Family Emergency', 'Without Notice'];
    const leaveTypes = ['Sick Leave', 'Casual Leave', 'Medical Leave'];
    final worker = workers[workerIndex];
    final status = statuses[(workerIndex + daysAgo) % statuses.length];
    final date = _guestAttendanceDate(daysAgo);
    final leaveType = leaveTypes[(workerIndex + daysAgo) % leaveTypes.length];
    final reason = status == 'Absent'
        ? absentReasons[(workerIndex + daysAgo) % absentReasons.length]
        : status == 'Leave'
        ? leaveType
        : '';

    return {
      'id': 'guest_attendance_${worker['workerId']}_$date',
      'workerId': worker['workerId'],
      'name': worker['name'],
      'email': worker['email'],
      'date': date,
      'attendanceDate': date,
      'status': status,
      'reason': reason,
      // These rows exist to populate the guest attendance tabs only. Leave
      // types shown on the dashboard must continue to come from time-off data.
      'excludeFromLeaveChart': true,
      if (status == 'Leave') 'type': leaveType,
    };
  }

  static final List<Map<String, dynamic>> attendance = [
    for (var daysAgo = 0; daysAgo < 7; daysAgo++)
      for (var workerIndex = 0; workerIndex < workers.length; workerIndex++)
        _guestAttendanceRecord(workerIndex, daysAgo),
  ];

  static final List<Map<String, dynamic>> payroll = [
    {
      'workerId': '0',
      'workerName': 'Michael Johnson',
      'salary': 95000,
      'amount': 7916.67,
      'status': 'paid',
      'period': 'Jan 2026',
      'currency': 'USD',
      'createdAt': '05/01/2026',
    },
    {
      'workerId': '1',
      'workerName': 'Sophia Martinez',
      'salary': 88000,
      'amount': 7333.33,
      'status': 'paid',
      'period': 'Jan 2026',
      'currency': 'USD',
      'createdAt': '12/01/2026',
    },
    {
      'workerId': '2',
      'workerName': 'Daniel Anderson',
      'salary': 82000,
      'amount': 6833.33,
      'status': 'unpaid',
      'period': 'Jan 2026',
      'currency': 'USD',
      'createdAt': '20/01/2026',
    },
    {
      'workerId': '3',
      'workerName': 'Olivia Thomas',
      'salary': 78000,
      'amount': 6500.00,
      'status': 'paid',
      'period': 'Feb 2026',
      'currency': 'USD',
      'createdAt': '03/02/2026',
    },
    {
      'workerId': '4',
      'workerName': 'James Miller',
      'salary': 110000,
      'amount': 9166.67,
      'status': 'unpaid',
      'period': 'Feb 2026',
      'currency': 'USD',
      'createdAt': '14/02/2026',
    },
    {
      'workerId': '5',
      'workerName': 'Emily Davis',
      'salary': 65000,
      'amount': 5416.67,
      'status': 'paid',
      'period': 'Feb 2026',
      'currency': 'USD',
      'createdAt': '25/02/2026',
    },
    {
      'workerId': '6',
      'workerName': 'William Brown',
      'salary': 120000,
      'amount': 10000.00,
      'status': 'paid',
      'period': 'Mar 2026',
      'currency': 'USD',
      'createdAt': '08/03/2026',
    },
    {
      'workerId': '7',
      'workerName': 'Amelia White',
      'salary': 62000,
      'amount': 5166.67,
      'status': 'unpaid',
      'period': 'Mar 2026',
      'currency': 'USD',
      'createdAt': '15/03/2026',
    },
    {
      'workerId': '8',
      'workerName': 'Charlotte Martin',
      'salary': 95000,
      'amount': 7916.67,
      'status': 'paid',
      'period': 'Mar 2026',
      'currency': 'USD',
      'createdAt': '22/03/2026',
    },
    {
      'workerId': '9',
      'workerName': 'Harper Garcia',
      'salary': 72000,
      'amount': 6000.00,
      'status': 'unpaid',
      'period': 'Apr 2026',
      'currency': 'USD',
      'createdAt': '05/04/2026',
    },
    {
      'workerId': '10',
      'workerName': 'Benjamin Harris',
      'salary': 85000,
      'amount': 7083.33,
      'status': 'paid',
      'period': 'Apr 2026',
      'currency': 'USD',
      'createdAt': '20/04/2026',
    },
    {
      'workerId': '11',
      'workerName': 'Lucas Taylor',
      'salary': 135000,
      'amount': 11250.00,
      'status': 'paid',
      'period': 'May 2026',
      'currency': 'USD',
      'createdAt': '10/05/2026',
    },
    {
      'workerId': '12',
      'workerName': 'Ethan Clark',
      'salary': 75000,
      'amount': 6250.00,
      'status': 'unpaid',
      'period': 'May 2026',
      'currency': 'USD',
      'createdAt': '25/05/2026',
    },
    {
      'workerId': '13',
      'workerName': 'Mia Robinson',
      'salary': 58000,
      'amount': 4833.33,
      'status': 'paid',
      'period': 'Jun 2026',
      'currency': 'USD',
      'createdAt': '05/06/2026',
    },
    {
      'workerId': '14',
      'workerName': 'Alexander Lee',
      'salary': 140000,
      'amount': 11666.67,
      'status': 'paid',
      'period': 'Jun 2026',
      'currency': 'USD',
      'createdAt': '20/06/2026',
    },
    {
      'workerId': '15',
      'workerName': 'Isabella Walker',
      'salary': 80000,
      'amount': 6666.67,
      'status': 'unpaid',
      'period': 'Jul 2026',
      'currency': 'USD',
      'createdAt': '10/07/2026',
    },
    {
      'workerId': '16',
      'workerName': 'John Smith',
      'salary': 95000,
      'amount': 7916.67,
      'status': 'paid',
      'period': 'Jul 2026',
      'currency': 'USD',
      'createdAt': '25/07/2026',
    },
    {
      'workerId': '17',
      'workerName': 'Noah Wilson',
      'salary': 125000,
      'amount': 10416.67,
      'status': 'unpaid',
      'period': 'Aug 2026',
      'currency': 'USD',
      'createdAt': '05/08/2026',
    },
    {
      'workerId': '18',
      'workerName': 'Ava Turner',
      'salary': 105000,
      'amount': 8750.00,
      'status': 'paid',
      'period': 'Aug 2026',
      'currency': 'USD',
      'createdAt': '20/08/2026',
    },
    {
      'workerId': '19',
      'workerName': 'Emma Wilson',
      'salary': 55000,
      'amount': 4583.33,
      'status': 'unpaid',
      'period': 'Sep 2026',
      'currency': 'USD',
      'createdAt': '10/09/2026',
    },
    
    {
      'workerId': '0',
      'workerName': 'Michael Johnson',
      'salary': 95000,
      'amount': 7916.67,
      'status': 'paid',
      'period': 'Oct 2026',
      'currency': 'USD',
      'createdAt': '05/10/2026',
    },
    {
      'workerId': '3',
      'workerName': 'Olivia Thomas',
      'salary': 78000,
      'amount': 6500.00,
      'status': 'paid',
      'period': 'Oct 2026',
      'currency': 'USD',
      'createdAt': '12/10/2026',
    },
    {
      'workerId': '6',
      'workerName': 'William Brown',
      'salary': 120000,
      'amount': 10000.00,
      'status': 'paid',
      'period': 'Oct 2026',
      'currency': 'USD',
      'createdAt': '20/10/2026',
    },
    {
      'workerId': '10',
      'workerName': 'Benjamin Harris',
      'salary': 85000,
      'amount': 7083.33,
      'status': 'unpaid',
      'period': 'Oct 2026',
      'currency': 'USD',
      'createdAt': '25/10/2026',
    },
    
    {
      'workerId': '1',
      'workerName': 'Sophia Martinez',
      'salary': 88000,
      'amount': 7333.33,
      'status': 'paid',
      'period': 'Nov 2026',
      'currency': 'USD',
      'createdAt': '05/11/2026',
    },
    {
      'workerId': '5',
      'workerName': 'Emily Davis',
      'salary': 65000,
      'amount': 5416.67,
      'status': 'unpaid',
      'period': 'Nov 2026',
      'currency': 'USD',
      'createdAt': '14/11/2026',
    },
    {
      'workerId': '8',
      'workerName': 'Charlotte Martin',
      'salary': 95000,
      'amount': 7916.67,
      'status': 'paid',
      'period': 'Nov 2026',
      'currency': 'USD',
      'createdAt': '20/11/2026',
    },
    {
      'workerId': '12',
      'workerName': 'Ethan Clark',
      'salary': 75000,
      'amount': 6250.00,
      'status': 'paid',
      'period': 'Nov 2026',
      'currency': 'USD',
      'createdAt': '25/11/2026',
    },
    
    {
      'workerId': '2',
      'workerName': 'Daniel Anderson',
      'salary': 82000,
      'amount': 6833.33,
      'status': 'paid',
      'period': 'Dec 2026',
      'currency': 'USD',
      'createdAt': '05/12/2026',
    },
    {
      'workerId': '7',
      'workerName': 'Amelia White',
      'salary': 62000,
      'amount': 5166.67,
      'status': 'unpaid',
      'period': 'Dec 2026',
      'currency': 'USD',
      'createdAt': '10/12/2026',
    },
    {
      'workerId': '15',
      'workerName': 'Isabella Walker',
      'salary': 80000,
      'amount': 6666.67,
      'status': 'paid',
      'period': 'Dec 2026',
      'currency': 'USD',
      'createdAt': '15/12/2026',
    },
    {
      'workerId': '19',
      'workerName': 'Emma Wilson',
      'salary': 55000,
      'amount': 4583.33,
      'status': 'unpaid',
      'period': 'Dec 2026',
      'currency': 'USD',
      'createdAt': '20/12/2026',
    },
  ];

  static final Map<String, List<Map<String, dynamic>>> holidays = {
    '2026': [
      {
        'name': "New Year's Day",
        'date': '01/01/2026',
      },
      {
        'name': 'Martin Luther King Jr. Day',
        'date': '19/01/2026',
      },
      {
        'name': 'Valentine\'s Day',
        'date': '14/02/2026',
      },
      {
        'name': 'Presidents\' Day',
        'date': '16/02/2026',
      },
      {
        'name': 'Spring Equinox',
        'date': '20/03/2026',
      },
      {
        'name': 'Easter Sunday',
        'date': '05/04/2026',
      },
      {
        'name': 'Earth Day',
        'date': '22/04/2026',
      },
      {
        'name': 'Memorial Day',
        'date': '25/05/2026',
      },
      {
        'name': 'Juneteenth',
        'date': '19/06/2026',
      },
      {
        'name': 'Independence Day',
        'date': '04/07/2026',
      },
      {
        'name': 'National Intern Day',
        'date': '30/07/2026',
      },
      {
        'name': 'International Cat Day',
        'date': '08/08/2026',
      },
      {
        'name': 'Summer Picnic',
        'date': '14/08/2026',
      },
      {
        'name': 'World Photography Day',
        'date': '19/08/2026',
      },
      {
        'name': 'Women\'s Equality Day',
        'date': '26/08/2026',
      },
      {
        'name': 'Labor Day',
        'date': '07/09/2026',
      },
      {
        'name': 'Patriot Day',
        'date': '11/09/2026',
      },
      {
        'name': 'International Day of Peace',
        'date': '21/09/2026',
      },
      {
        'name': 'World Teachers\' Day',
        'date': '05/10/2026',
      },
      {
        'name': 'Columbus Day',
        'date': '12/10/2026',
      },
      {
        'name': 'United Nations Day',
        'date': '24/10/2026',
      },
      {
        'name': 'Halloween',
        'date': '31/10/2026',
      },
      {
        'name': 'Veterans Day',
        'date': '11/11/2026',
      },
      {
        'name': 'World Kindness Day',
        'date': '13/11/2026',
      },
      {
        'name': 'Thanksgiving Day',
        'date': '26/11/2026',
      },
      {
        'name': 'Black Friday',
        'date': '27/11/2026',
      },
      {
        'name': 'Human Rights Day',
        'date': '10/12/2026',
      },
      {
        'name': 'Winter Solstice',
        'date': '21/12/2026',
      },
      {
        'name': 'Christmas Eve',
        'date': '24/12/2026',
      },
      {
        'name': 'Christmas Day',
        'date': '25/12/2026',
      },
      {
        'name': 'Boxing Day',
        'date': '26/12/2026',
      },
      {
        'name': 'New Year\'s Eve',
        'date': '31/12/2026',
      },
    ],
  };

  static final List<Map<String, dynamic>> timeoff = [
    {
      'workerId': '0',
      'name': 'Michael Johnson',
      'type': 'Sick Leave',
      'startDate': '15/01/2026',
      'endDate': '17/01/2026',
      'notes': 'Doctor appointment',
      'status': 'assigned',
    },

    {
      'workerId': '7',
      'name': 'Amelia White',
      'type': 'Medical Leave',
      'startDate': '05/02/2026',
      'endDate': '06/02/2026',
      'notes': 'Feeling unwell',
      'status': 'assigned',
    },
    {
      'workerId': '12',
      'name': 'Ethan Clark',
      'type': 'Medical Leave',
      'startDate': '22/01/2026',
      'endDate': '26/01/2026',
      'notes': 'Surgery follow-up',
      'status': 'assigned',
    },
    {
      'workerId': '19',
      'name': 'Emma Wilson',
      'type': 'Casual Leave',
      'startDate': '03/02/2026',
      'endDate': '04/02/2026',
      'notes': 'Personal errand',
      'status': 'assigned',
    },

    {
      'workerId': '3',
      'name': 'Olivia Thomas',
      'type': 'Casual Leave',
      'startDate': '28/01/2026',
      'endDate': '29/01/2026',
      'notes': 'Migraine',
      'status': 'assigned',
    },
    {
      'workerId': '4',
      'name': 'James Miller',
      'type': 'Sick Leave',
      'startDate': '10/03/2026',
      'endDate': '11/03/2026',
      'notes': 'Fever',
      'status': 'assigned',
    },
  ];

  static final List<Map<String, dynamic>> notifications = [
    {
      'type': 'welcome',
      'data': {'name': 'to HRMS'},
    },
    {
      'type': 'attendance_marked',
      'data': {'name': '15 employees'},
    },
    {
      'type': 'time_off_added',
      'data': {'name': 'Michael Johnson', 'type': 'Sick Leave'},
    },
    {
      'type': 'payroll_added',
      'data': {'name': 'June 2026'},
    },
    {
      'type': 'holiday_added',
      'data': {'name': 'Independence Day'},
    },
    {
      'type': 'expense_added',
      'data': {'amount': '\$475.00'},
    },
    {
      'type': 'expense_added',
      'data': {'amount': '\$124.50'},
    },
    {
      'type': 'asset_added',
      'data': {'type': 'MacBook Pro', 'name': 'Sophia Martinez'},
    },
  ];

  static final List<Map<String, dynamic>> assets = [
    {
      'name': 'John Smith',
      'position': 'Senior Web Developer',
      'type': 'MacBook Pro',
      'dateLoaned': '15/03/2024',
      'dateReturned': 'in_use',
      'isReturned': false,
      'profileImage': 'assets/boy.png',
    },
    {
      'name': 'Michael Johnson',
      'position': 'DevOps Engineer',
      'type': 'Dell Monitor',
      'dateLoaned': '01/06/2024',
      'dateReturned': 'in_use',
      'isReturned': false,
      'profileImage': 'assets/boy.png',
    },
    {
      'name': 'Sophia Martinez',
      'position': 'HR Manager',
      'type': 'iPhone 15',
      'dateLoaned': '10/09/2024',
      'dateReturned': 'in_use',
      'isReturned': false,
      'profileImage': 'assets/boy.png',
    },
    {
      'name': 'Daniel Anderson',
      'position': 'Frontend Developer',
      'type': 'Mechanical Keyboard',
      'dateLoaned': '20/07/2024',
      'dateReturned': 'in_use',
      'isReturned': false,
      'profileImage': 'assets/boy.png',
    },
    {
      'name': 'Olivia Thomas',
      'position': 'UI Designer',
      'type': 'iPad Pro',
      'dateLoaned': '05/11/2024',
      'dateReturned': 'in_use',
      'isReturned': false,
      'profileImage': 'assets/boy.png',
    },
    {
      'name': 'James Miller',
      'position': 'Backend Engineer',
      'type': 'Standing Desk',
      'dateLoaned': '12/12/2024',
      'dateReturned': '12/12/2024',
      'isReturned': true,
      'profileImage': 'assets/boy.png',
    },
    {
      'name': 'Emily Davis',
      'position': 'Data Analyst',
      'type': 'Laptop',
      'dateLoaned': '15/01/2025',
      'dateReturned': 'in_use',
      'isReturned': false,
      'profileImage': 'assets/imageplaceholder.png',
    },
    {
      'name': 'William Brown',
      'position': 'Product Manager',
      'type': 'Monitor',
      'dateLoaned': '20/02/2025',
      'dateReturned': 'in_use',
      'isReturned': false,
      'profileImage': 'assets/imageplaceholder.png',
    },
    {
      'name': 'Amelia White',
      'position': 'Graphic Designer',
      'type': 'Mouse',
      'dateLoaned': '10/03/2025',
      'dateReturned': 'in_use',
      'isReturned': false,
      'profileImage': 'assets/boy.png',
    },
    {
      'name': 'Charlotte Martin',
      'position': 'Cyber Security Analyst',
      'type': 'Keyboard',
      'dateLoaned': '20/05/2025',
      'dateReturned': '20/05/2025',
      'isReturned': true,
      'profileImage': 'assets/imageplaceholder.png',
    },
    {
      'name': 'Sophia Martinez',
      'position': 'HR Manager',
      'type': 'Mac',
      'dateLoaned': '05/02/2025',
      'dateReturned': 'in_use',
      'isReturned': false,
      'profileImage': 'assets/boy.png',
    },
    {
      'name': 'Daniel Anderson',
      'position': 'Frontend Developer',
      'type': 'Table',
      'dateLoaned': '12/04/2025',
      'dateReturned': 'in_use',
      'isReturned': false,
      'profileImage': 'assets/imageplaceholder.png',
    },
    {
      'name': 'John Smith',
      'position': 'Backend Developer',
      'type': 'Monitor',
      'dateLoaned': '18/06/2025',
      'dateReturned': 'in_use',
      'isReturned': false,
      'profileImage': 'assets/boy.png',
    },
    {
      'name': 'Michael Johnson',
      'position': 'DevOps Engineer',
      'type': 'Headphone',
      'dateLoaned': '22/06/2025',
      'dateReturned': '22/06/2025',
      'isReturned': true,
      'profileImage': 'assets/imageplaceholder.png',
    },
    {
      'name': 'Olivia Thomas',
      'position': 'UI Designer',
      'type': 'iPad',
      'dateLoaned': '01/07/2025',
      'dateReturned': 'in_use',
      'isReturned': false,
      'profileImage': 'assets/boy.png',
    },
    {
      'name': 'James Miller',
      'position': 'Backend Engineer',
      'type': 'Laptop',
      'dateLoaned': '05/07/2025',
      'dateReturned': '05/07/2025',
      'isReturned': true,
      'profileImage': 'assets/imageplaceholder.png',
    },
    {
      'name': 'Harper Garcia',
      'position': 'Technical Writer',
      'type': 'Keyboard',
      'dateLoaned': '10/08/2025',
      'dateReturned': 'in_use',
      'isReturned': false,
      'profileImage': 'assets/boy.png',
    },
    {
      'name': 'Benjamin Harris',
      'position': 'Mobile Developer',
      'type': 'iPhone',
      'dateLoaned': '15/08/2025',
      'dateReturned': 'in_use',
      'isReturned': false,
      'profileImage': 'assets/imageplaceholder.png',
    },
    {
      'name': 'Lucas Taylor',
      'position': 'Solutions Architect',
      'type': 'Monitor',
      'dateLoaned': '20/09/2025',
      'dateReturned': '20/09/2025',
      'isReturned': true,
      'profileImage': 'assets/boy.png',
    },
  ];
}
