class DummyData {
  static final List<Map<String, dynamic>> workers = [
    {
      'id': 'dummy_1',
      'name': 'John Smith',
      'email': 'john.smith@stark.com',
      'type1': 'Full-Time',
      'position': 'Senior Web Developer',
      'type2': 'Remote',
    },
    {
      'id': 'dummy_2',
      'name': 'Michael Johnson',
      'email': 'michael.johnson@stark.com',
      'type1': 'Full-Time',
      'position': 'UI/UX Designer',
      'type2': 'On-Site',
    },
    {
      'id': 'dummy_3',
      'name': 'Robert Wilson',
      'email': 'robert.wilson@stark.com',
      'type1': 'Contract',
      'position': 'DevOps Engineer',
      'type2': 'On-Site',
    },
    {
      'id': 'dummy_4',
      'name': 'Emily Davis',
      'email': 'emily.davis@stark.com',
      'type1': 'Full-Time',
      'position': 'Product Manager',
      'type2': 'On-Site',
    },
    {
      'id': 'dummy_5',
      'name': 'David Brown',
      'email': 'david.brown@stark.com',
      'type1': 'Part-Time',
      'position': 'Marketing Specialist',
      'type2': 'Remote',
    },
    {
      'id': 'dummy_6',
      'name': 'James Miller',
      'email': 'james.miller@stark.com',
      'type1': 'Full-Time',
      'position': 'Backend Engineer',
      'type2': 'Remote',
    },
    {
      'id': 'dummy_7',
      'name': 'Sophia Martinez',
      'email': 'sophia.martinez@stark.com',
      'type1': 'Full-Time',
      'position': 'HR Manager',
      'type2': 'On-Site',
    },
    {
      'id': 'dummy_8',
      'name': 'Daniel Anderson',
      'email': 'daniel.anderson@stark.com',
      'type1': 'Contract',
      'position': 'Frontend Developer',
      'type2': 'Remote',
    },
    {
      'id': 'dummy_9',
      'name': 'Olivia Thomas',
      'email': 'olivia.thomas@stark.com',
      'type1': 'Full-Time',
      'position': 'QA Engineer',
      'type2': 'On-Site',
    },
    {
      'id': 'dummy_10',
      'name': 'Lucas Taylor',
      'email': 'lucas.taylor@stark.com',
      'type1': 'Full-Time',
      'position': 'Solutions Architect',
      'type2': 'On-Site',
    },
    {
      'id': 'dummy_11',
      'name': 'Amelia White',
      'email': 'amelia.white@stark.com',
      'type1': 'Part-Time',
      'position': 'Graphic Designer',
      'type2': 'Remote',
    },
    {
      'id': 'dummy_12',
      'name': 'Benjamin Harris',
      'email': 'benjamin.harris@stark.com',
      'type1': 'Full-Time',
      'position': 'Mobile Developer',
      'type2': 'Remote',
    },
    {
      'id': 'dummy_13',
      'name': 'Charlotte Martin',
      'email': 'charlotte.martin@stark.com',
      'type1': 'Full-Time',
      'position': 'Cyber Security Analyst',
      'type2': 'On-Site',
    },
    {
      'id': 'dummy_14',
      'name': 'Henry Thompson',
      'email': 'henry.thompson@stark.com',
      'type1': 'Contract',
      'position': 'Data Scientist',
      'type2': 'Remote',
    },
    {
      'id': 'dummy_15',
      'name': 'Harper Garcia',
      'email': 'harper.garcia@stark.com',
      'type1': 'Part-Time',
      'position': 'Technical Writer',
      'type2': 'Remote',
    },
  ];

  static final List<Map<String, dynamic>> expenses = [
    {
      'id': 'dummy_e1',
      'name': 'John Smith',
      'date': '05/06/2026',
      'category': 'Client Dinner',
      'amount': 124.50,
    },
    {
      'id': 'dummy_e2',
      'name': 'Michael Johnson',
      'date': '04/06/2026',
      'category': 'Figma Subscription',
      'amount': 45.00,
    },
    {
      'id': 'dummy_e3',
      'name': 'Emily Davis',
      'date': '02/06/2026',
      'category': 'Office Keyboard',
      'amount': 89.99,
    },
    {
      'id': 'dummy_e4',
      'name': 'Robert Wilson',
      'date': '01/06/2026',
      'category': 'AWS Cloud Hosting',
      'amount': 250.00,
    },
    {
      'id': 'dummy_e5',
      'name': 'David Brown',
      'date': '28/05/2026',
      'category': 'Google Ads Campaign',
      'amount': 500.00,
    },
    {
      'id': 'dummy_e6',
      'name': 'James Miller',
      'date': '25/05/2026',
      'category': 'GitHub Enterprise',
      'amount': 150.00,
    },
    {
      'id': 'dummy_e7',
      'name': 'Sophia Martinez',
      'date': '22/05/2026',
      'category': 'Recruiting Software',
      'amount': 320.00,
    },
    {
      'id': 'dummy_e8',
      'name': 'Daniel Anderson',
      'date': '19/05/2026',
      'category': 'Internet Allowance',
      'amount': 60.00,
    },
    {
      'id': 'dummy_e9',
      'name': 'Olivia Thomas',
      'date': '15/05/2026',
      'category': 'Testing Device',
      'amount': 299.00,
    },
    {
      'id': 'dummy_e10',
      'name': 'Lucas Taylor',
      'date': '10/05/2026',
      'category': 'Office Chair',
      'amount': 180.00,
    },
    {
      'id': 'dummy_e11',
      'name': 'Amelia White',
      'date': '08/05/2026',
      'category': 'Adobe CC Suite',
      'amount': 79.99,
    },
    {
      'id': 'dummy_e12',
      'name': 'John Smith',
      'date': '05/05/2026',
      'category': 'Conference Tickets',
      'amount': 400.00,
    },
    {
      'id': 'dummy_e13',
      'name': 'Benjamin Harris',
      'date': '06/06/2026',
      'category': 'Apple Developer Account',
      'amount': 99.00,
    },
    {
      'id': 'dummy_e14',
      'name': 'Charlotte Martin',
      'date': '05/06/2026',
      'category': 'YubiKey Security Key',
      'amount': 55.00,
    },
    {
      'id': 'dummy_e15',
      'name': 'Henry Thompson',
      'date': '03/06/2026',
      'category': 'Data Camp Subscription',
      'amount': 150.00,
    },
  ];

  static final List<Map<String, dynamic>> attendance = [
    {
      'id': 'dummy_a1',
      'name': 'John Smith',
      'email': 'john.smith@stark.com',
      'role': 'Senior Web Developer',
      'status': 'Present',
      'attendanceType': 'Remote',
      'workType': 'Full Time',
    },
    {
      'id': 'dummy_a2',
      'name': 'Michael Johnson',
      'email': 'michael.johnson@stark.com',
      'role': 'UI/UX Designer',
      'status': 'Present',
      'attendanceType': 'On-Site',
      'workType': 'Full Time',
    },
    {
      'id': 'dummy_a3',
      'name': 'Robert Wilson',
      'email': 'robert.wilson@stark.com',
      'role': 'DevOps Engineer',
      'status': 'Absent',
      'attendanceType': 'On-Site',
      'workType': 'Contract',
    },
    {
      'id': 'dummy_a4',
      'name': 'Emily Davis',
      'email': 'emily.davis@stark.com',
      'role': 'Product Manager',
      'status': 'Present',
      'attendanceType': 'On-Site',
      'workType': 'Full Time',
    },
    {
      'id': 'dummy_a5',
      'name': 'David Brown',
      'email': 'david.brown@stark.com',
      'role': 'Marketing Specialist',
      'status': 'Leave',
      'attendanceType': 'Remote',
      'workType': 'Part Time',
    },
    {
      'id': 'dummy_a6',
      'name': 'James Miller',
      'email': 'james.miller@stark.com',
      'role': 'Backend Engineer',
      'status': 'Present',
      'attendanceType': 'Remote',
      'workType': 'Full Time',
    },
    {
      'id': 'dummy_a7',
      'name': 'Sophia Martinez',
      'email': 'sophia.martinez@stark.com',
      'role': 'HR Manager',
      'status': 'Present',
      'attendanceType': 'On-Site',
      'workType': 'Full Time',
    },
    {
      'id': 'dummy_a8',
      'name': 'Daniel Anderson',
      'email': 'daniel.anderson@stark.com',
      'role': 'Frontend Developer',
      'status': 'Present',
      'attendanceType': 'Remote',
      'workType': 'Contract',
    },
    {
      'id': 'dummy_a9',
      'name': 'Olivia Thomas',
      'email': 'olivia.thomas@stark.com',
      'role': 'QA Engineer',
      'status': 'Present',
      'attendanceType': 'On-Site',
      'workType': 'Full Time',
    },
    {
      'id': 'dummy_a10',
      'name': 'Lucas Taylor',
      'email': 'lucas.taylor@stark.com',
      'role': 'Solutions Architect',
      'status': 'Absent',
      'attendanceType': 'On-Site',
      'workType': 'Full Time',
    },
    {
      'id': 'dummy_a11',
      'name': 'Amelia White',
      'email': 'amelia.white@stark.com',
      'role': 'Graphic Designer',
      'status': 'Leave',
      'attendanceType': 'Remote',
      'workType': 'Part Time',
      'type': 'Sick Leave',
      'desc':
          'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabuyweeygewegecechvchvecjjecbejcbecbcbygeygeyeccugewgyugwgfygygweyg',
    },
    {
      'id': 'dummy_a12',
      'name': 'Benjamin Harris',
      'email': 'benjamin.harris@stark.com',
      'role': 'Mobile Developer',
      'status': 'Present',
      'attendanceType': 'Remote',
      'workType': 'Full Time',
    },
    {
      'id': 'dummy_a13',
      'name': 'Charlotte Martin',
      'email': 'charlotte.martin@stark.com',
      'role': 'Cyber Security Analyst',
      'status': 'Present',
      'attendanceType': 'On-Site',
      'workType': 'Full Time',
    },
    {
      'id': 'dummy_a14',
      'name': 'Henry Thompson',
      'email': 'henry.thompson@stark.com',
      'role': 'Data Scientist',
      'status': 'Absent',
      'attendanceType': 'Remote',
      'workType': 'Contract',
    },
    {
      'id': 'dummy_a15',
      'name': 'Harper Garcia',
      'email': 'harper.garcia@stark.com',
      'role': 'Technical Writer',
      'status': 'Leave',
      'attendanceType': 'Remote',
      'workType': 'Part Time',
    },
  ];

  static final List<Map<String, dynamic>> payroll = [
    {
      'id': 'dummy_p1',
      'name': 'John Smith',
      'email': 'john.smith@stark.com',
      'position': 'Senior Web Developer',
      'contact': '+1 555-0101',
      'status': 'Active',
      'totalWorkDays': '240',
      'absents': '04',
      'leaves': '08',
      'overtimeDays': '12',
      'salary': '\$ 95,000',
    },
    {
      'id': 'dummy_p2',
      'name': 'Michael Johnson',
      'email': 'michael.johnson@stark.com',
      'position': 'UI/UX Designer',
      'contact': '+1 555-0102',
      'status': 'Active',
      'totalWorkDays': '230',
      'absents': '02',
      'leaves': '06',
      'overtimeDays': '05',
      'salary': '\$ 75,000',
    },
    {
      'id': 'dummy_p3',
      'name': 'Robert Wilson',
      'email': 'robert.wilson@stark.com',
      'position': 'DevOps Engineer',
      'contact': '+1 555-0103',
      'status': 'Active',
      'totalWorkDays': '120',
      'absents': '01',
      'leaves': '02',
      'overtimeDays': '00',
      'salary': '\$ 85,000',
    },
    {
      'id': 'dummy_p4',
      'name': 'Emily Davis',
      'email': 'emily.davis@stark.com',
      'position': 'Product Manager',
      'contact': '+1 555-0104',
      'status': 'Active',
      'totalWorkDays': '250',
      'absents': '01',
      'leaves': '10',
      'overtimeDays': '15',
      'salary': '\$ 110,000',
    },
    {
      'id': 'dummy_p5',
      'name': 'David Brown',
      'email': 'david.brown@stark.com',
      'position': 'Marketing Specialist',
      'contact': '+1 555-0105',
      'status': 'Active',
      'totalWorkDays': '180',
      'absents': '05',
      'leaves': '12',
      'overtimeDays': '02',
      'salary': '\$ 60,000',
    },
    {
      'id': 'dummy_p6',
      'name': 'James Miller',
      'email': 'james.miller@stark.com',
      'position': 'Backend Engineer',
      'contact': '+1 555-0106',
      'status': 'Active',
      'totalWorkDays': '220',
      'absents': '03',
      'leaves': '05',
      'overtimeDays': '08',
      'salary': '\$ 80,000',
    },
    {
      'id': 'dummy_p7',
      'name': 'Sophia Martinez',
      'email': 'sophia.martinez@stark.com',
      'position': 'HR Manager',
      'contact': '+1 555-0107',
      'status': 'Active',
      'totalWorkDays': '240',
      'absents': '00',
      'leaves': '04',
      'overtimeDays': '02',
      'salary': '\$ 70,000',
    },
    {
      'id': 'dummy_p8',
      'name': 'Daniel Anderson',
      'email': 'daniel.anderson@stark.com',
      'position': 'Frontend Developer',
      'contact': '+1 555-0108',
      'status': 'Active',
      'totalWorkDays': '150',
      'absents': '02',
      'leaves': '03',
      'overtimeDays': '04',
      'salary': '\$ 65,000',
    },
    {
      'id': 'dummy_p9',
      'name': 'Olivia Thomas',
      'email': 'olivia.thomas@stark.com',
      'position': 'QA Engineer',
      'contact': '+1 555-0109',
      'status': 'Active',
      'totalWorkDays': '245',
      'absents': '01',
      'leaves': '05',
      'overtimeDays': '06',
      'salary': '\$ 68,000',
    },
    {
      'id': 'dummy_p10',
      'name': 'Lucas Taylor',
      'email': 'lucas.taylor@stark.com',
      'position': 'Solutions Architect',
      'contact': '+1 555-0110',
      'status': 'Active',
      'totalWorkDays': '210',
      'absents': '04',
      'leaves': '08',
      'overtimeDays': '10',
      'salary': '\$ 120,000',
    },
    {
      'id': 'dummy_p11',
      'name': 'Amelia White',
      'email': 'amelia.white@stark.com',
      'position': 'Graphic Designer',
      'contact': '+1 555-0111',
      'status': 'Active',
      'totalWorkDays': '160',
      'absents': '03',
      'leaves': '15',
      'overtimeDays': '01',
      'salary': '\$ 55,000',
    },
    {
      'id': 'dummy_p12',
      'name': 'Benjamin Harris',
      'email': 'benjamin.harris@stark.com',
      'position': 'Mobile Developer',
      'contact': '+1 555-0112',
      'status': 'Active',
      'totalWorkDays': '220',
      'absents': '02',
      'leaves': '05',
      'overtimeDays': '10',
      'salary': '\$ 88,000',
    },
    {
      'id': 'dummy_p13',
      'name': 'Charlotte Martin',
      'email': 'charlotte.martin@stark.com',
      'position': 'Cyber Security Analyst',
      'contact': '+1 555-0113',
      'status': 'Active',
      'totalWorkDays': '240',
      'absents': '01',
      'leaves': '04',
      'overtimeDays': '02',
      'salary': '\$ 90,000',
    },
    {
      'id': 'dummy_p14',
      'name': 'Henry Thompson',
      'email': 'henry.thompson@stark.com',
      'position': 'Data Scientist',
      'contact': '+1 555-0114',
      'status': 'Active',
      'totalWorkDays': '125',
      'absents': '01',
      'leaves': '03',
      'overtimeDays': '00',
      'salary': '\$ 95,000',
    },
    {
      'id': 'dummy_p15',
      'name': 'Harper Garcia',
      'email': 'harper.garcia@stark.com',
      'position': 'Technical Writer',
      'contact': '+1 555-0115',
      'status': 'Active',
      'totalWorkDays': '150',
      'absents': '03',
      'leaves': '12',
      'overtimeDays': '01',
      'salary': '\$ 48,000',
    },
  ];

  static final List<Map<String, dynamic>> timeoff = [
    {
      'id': 'dummy_t1',
      'name': 'John Smith',
      'email': 'john.smith@stark.com',
      'position': 'Senior Web Developer',
      'contact': '+1 555-0101',
      'action': 'Annual Leave',
    },
    {
      'id': 'dummy_t2',
      'name': 'Michael Johnson',
      'email': 'michael.johnson@stark.com',
      'position': 'UI/UX Designer',
      'contact': '+1 555-0102',
      'action': 'Sick Leave',
    },
    {
      'id': 'dummy_t3',
      'name': 'Robert Wilson',
      'email': 'robert.wilson@stark.com',
      'position': 'DevOps Engineer',
      'contact': '+1 555-0103',
      'action': 'Casual Leave',
    },
    {
      'id': 'dummy_t4',
      'name': 'David Brown',
      'email': 'david.brown@stark.com',
      'position': 'Marketing Specialist',
      'contact': '+1 555-0105',
      'action': 'Maternity Leave',
    },
    {
      'id': 'dummy_t5',
      'name': 'James Miller',
      'email': 'james.miller@stark.com',
      'position': 'Backend Engineer',
      'contact': '+1 555-0106',
      'action': 'Annual Leave',
    },
    {
      'id': 'dummy_t6',
      'name': 'Sophia Martinez',
      'email': 'sophia.martinez@stark.com',
      'position': 'HR Manager',
      'contact': '+1 555-0107',
      'action': 'Sick Leave',
    },
    {
      'id': 'dummy_t7',
      'name': 'Daniel Anderson',
      'email': 'daniel.anderson@stark.com',
      'position': 'Frontend Developer',
      'contact': '+1 555-0108',
      'action': 'Casual Leave',
    },
    {
      'id': 'dummy_t8',
      'name': 'Olivia Thomas',
      'email': 'olivia.thomas@stark.com',
      'position': 'QA Engineer',
      'contact': '+1 555-0109',
      'action': 'Maternity Leave',
    },
    {
      'id': 'dummy_t9',
      'name': 'Lucas Taylor',
      'email': 'lucas.taylor@stark.com',
      'position': 'Solutions Architect',
      'contact': '+1 555-0110',
      'action': 'Annual Leave',
    },
    {
      'id': 'dummy_t10',
      'name': 'Amelia White',
      'email': 'amelia.white@stark.com',
      'position': 'Graphic Designer',
      'contact': '+1 555-0111',
      'action': 'Sick Leave',
    },
    {
      'id': 'dummy_t11',
      'name': 'Benjamin Harris',
      'email': 'benjamin.harris@stark.com',
      'position': 'Mobile Developer',
      'contact': '+1 555-0112',
      'action': 'Annual Leave',
    },
    {
      'id': 'dummy_t12',
      'name': 'Charlotte Martin',
      'email': 'charlotte.martin@stark.com',
      'position': 'Cyber Security Analyst',
      'contact': '+1 555-0113',
      'action': 'Sick Leave',
    },
  ];

  static final Map<String, List<Map<String, dynamic>>> holidays = {
    'May': [
      {
        'day': 1,
        'month': 'May',
        'remainingDays': '05',
        'dayOfWeek': 'Saturday',
        'name': 'Labour Day',
        'isEnabled': true,
      },
      {
        'day': 3,
        'month': 'May',
        'remainingDays': '07',
        'dayOfWeek': 'Monday',
        'name': 'Eid-ul-Fitr Holiday',
        'isEnabled': false,
      },
      {
        'day': 6,
        'month': 'May',
        'remainingDays': '10',
        'dayOfWeek': 'Thursday',
        'name': 'Memorial Day',
        'isEnabled': false,
      },
      {
        'day': 10,
        'month': 'May',
        'remainingDays': '14',
        'dayOfWeek': 'Monday',
        'name': 'Eid-ul-Adha Holiday',
        'isEnabled': false,
      },
      {
        'day': 14,
        'month': 'May',
        'remainingDays': '18',
        'dayOfWeek': 'Sunday',
        'name': 'Mother\'s Day',
        'isEnabled': false,
      },
      {
        'day': 15,
        'month': 'May',
        'remainingDays': '19',
        'dayOfWeek': 'Monday',
        'name': 'Independence Day',
        'isEnabled': false,
      },
      {
        'day': 18,
        'month': 'May',
        'remainingDays': '22',
        'dayOfWeek': 'Thursday',
        'name': 'Founder\'s Day',
        'isEnabled': false,
      },
      {
        'day': 20,
        'month': 'May',
        'remainingDays': '24',
        'dayOfWeek': 'Saturday',
        'name': 'Spring Break',
        'isEnabled': false,
      },
      {
        'day': 22,
        'month': 'May',
        'remainingDays': '26',
        'dayOfWeek': 'Monday',
        'name': 'Youth Day',
        'isEnabled': false,
      },
      {
        'day': 25,
        'month': 'May',
        'remainingDays': '29',
        'dayOfWeek': 'Thursday',
        'name': 'National Day',
        'isEnabled': false,
      },
      {
        'day': 26,
        'month': 'May',
        'remainingDays': '30',
        'dayOfWeek': 'Friday',
        'name': 'Victoria Day',
        'isEnabled': false,
      },
      {
        'day': 28,
        'month': 'May',
        'remainingDays': '32',
        'dayOfWeek': 'Sunday',
        'name': 'Bank Holiday',
        'isEnabled': false,
      },
      {
        'day': 29,
        'month': 'May',
        'remainingDays': '33',
        'dayOfWeek': 'Monday',
        'name': 'Ascension Day',
        'isEnabled': false,
      },
      {
        'day': 30,
        'month': 'May',
        'remainingDays': '34',
        'dayOfWeek': 'Tuesday',
        'name': 'Unity Day',
        'isEnabled': false,
      },
      {
        'day': 31,
        'month': 'May',
        'remainingDays': '35',
        'dayOfWeek': 'Wednesday',
        'name': 'Memorial Feast',
        'isEnabled': false,
      },
    ],
    'Feb': [
      {
        'day': 1,
        'month': 'Feb',
        'remainingDays': '02',
        'dayOfWeek': 'Wednesday',
        'name': 'Groundhog Day',
        'isEnabled': false,
      },
      {
        'day': 6,
        'month': 'Feb',
        'remainingDays': '07',
        'dayOfWeek': 'Monday',
        'name': 'Super Bowl',
        'isEnabled': true,
      },
      {
        'day': 14,
        'month': 'Feb',
        'remainingDays': '15',
        'dayOfWeek': 'Tuesday',
        'name': 'Valentine\'s Day',
        'isEnabled': true,
      },
      {
        'day': 26,
        'month': 'Feb',
        'remainingDays': '27',
        'dayOfWeek': 'Monday',
        'name': 'Presidents\' Day',
        'isEnabled': true,
      },
    ],
  };

  static final List<Map<String, dynamic>> assets = [
    {
      'name': 'Olivia Vance',
      'position': 'Web Developer',
      'type': 'Laptop',
      'dateLoaned': '01/12/2022',
      'dateReturned': '01/12/2022',
      'isReturned': true,
    },
    {
      'name': 'Sophia Smith',
      'position': 'Graphic Designer',
      'type': 'Mouse',
      'dateLoaned': '01/12/2022',
      'dateReturned': 'In use',
      'isReturned': false,
    },
    {
      'name': 'Amelia Gray',
      'position': 'Engineering',
      'type': 'Keyboard',
      'dateLoaned': '01/12/2022',
      'dateReturned': '01/12/2022',
      'isReturned': true,
    },
    {
      'name': 'Olivia Vance',
      'position': 'Graphic Designer',
      'type': 'Mac',
      'dateLoaned': '01/12/2022',
      'dateReturned': 'In use',
      'isReturned': false,
    },
    {
      'name': 'Lucas Johnson',
      'position': 'Web Developer',
      'type': 'Table',
      'dateLoaned': '01/12/2022',
      'dateReturned': 'In use',
      'isReturned': false,
    },
  ];
}
