import 'dart:convert';
import 'package:easy_localization/easy_localization.dart';
import 'package:shared_preferences/shared_preferences.dart';

class DummyData {
  static const _dataVersionKey = 'dummy_data_version';
  static const _currentDataVersion = 5;

  static Future<void> loadFromPrefs() async {
    try {
      final prefs = await SharedPreferences.getInstance();

      final savedVersion = prefs.getInt(_dataVersionKey) ?? 0;
      if (savedVersion < _currentDataVersion) {
        await prefs.remove('dummy_workers');
        await prefs.remove('dummy_expenses');
        await prefs.remove('dummy_attendance');
        await prefs.remove('dummy_payroll');
        await prefs.remove('dummy_timeoff');
        await prefs.remove('dummy_assets');
        await prefs.remove('dummy_holidays');
        await prefs.setInt(_dataVersionKey, _currentDataVersion);
        return;
      }

      try {
        final workersJson = prefs.getString('dummy_workers');
        if (workersJson != null && workersJson.isNotEmpty) {
          final list = (jsonDecode(workersJson) as List)
              .cast<Map<String, dynamic>>();
          workers
            ..clear()
            ..addAll(list);
        }
      } catch (e) {}

      try {
        final expensesJson = prefs.getString('dummy_expenses');
        if (expensesJson != null && expensesJson.isNotEmpty) {
          final list = (jsonDecode(expensesJson) as List)
              .cast<Map<String, dynamic>>();
          final hasOldWorkerNames = list.any((e) {
            final name = (e['name'] ?? '').toString();
            return name == 'Michael Johnson' ||
                name == 'Emily Davis' ||
                name == 'Robert Wilson' ||
                name == 'David Brown' ||
                name == 'James Miller' ||
                name == 'Sophia Martinez' ||
                name == 'Daniel Anderson' ||
                name == 'Olivia Thomas' ||
                name == 'Lucas Taylor' ||
                name == 'Amelia White' ||
                name == 'John Smith' ||
                name == 'Benjamin Harris' ||
                name == 'Charlotte Martin' ||
                name == 'Henry Thompson' ||
                name == 'Sarah Connor' ||
                name == 'Mike Peters' ||
                name == 'Laura Palmer' ||
                name == 'Tom Hardy' ||
                name == 'Nina Dobrev' ||
                name == 'Ryan Gosling' ||
                name == 'Emma Watson' ||
                name == 'Chris Evans' ||
                name == 'Scarlett Johansson' ||
                name == 'Robert Downey';
          });
          if (!hasOldWorkerNames) {
            expenses
              ..clear()
              ..addAll(list);
          }
        }
      } catch (e) {
        // ignore
      }

      try {
        final attendanceJson = prefs.getString('dummy_attendance');
        if (attendanceJson != null && attendanceJson.isNotEmpty) {
          final list = (jsonDecode(attendanceJson) as List)
              .cast<Map<String, dynamic>>();
          attendance
            ..clear()
            ..addAll(list);
        }
      } catch (e) {
        // ignore
      }

      try {
        final payrollJson = prefs.getString('dummy_payroll');
        if (payrollJson != null && payrollJson.isNotEmpty) {
          final list = (jsonDecode(payrollJson) as List)
              .cast<Map<String, dynamic>>();
          payroll
            ..clear()
            ..addAll(list);
        }
      } catch (e) {
        // ignore
      }

      try {
        final timeoffJson = prefs.getString('dummy_timeoff');
        if (timeoffJson != null && timeoffJson.isNotEmpty) {
          final list = (jsonDecode(timeoffJson) as List)
              .cast<Map<String, dynamic>>();
          timeoff
            ..clear()
            ..addAll(list);
        }
      } catch (e) {
        // ignore
      }

      try {
        final assetsJson = prefs.getString('dummy_assets');
        if (assetsJson != null && assetsJson.isNotEmpty) {
          final list = (jsonDecode(assetsJson) as List)
              .cast<Map<String, dynamic>>();
          assets
            ..clear()
            ..addAll(list);
        }
      } catch (e) {
        // ignore
      }

      try {
        final holidaysJson = prefs.getString('dummy_holidays');
        if (holidaysJson != null && holidaysJson.isNotEmpty) {
          final decoded = jsonDecode(holidaysJson) as Map<String, dynamic>;
          holidays.clear();
          for (final entry in decoded.entries) {
            final list = (entry.value as List)
                .map((item) => Map<String, dynamic>.from(item as Map))
                .toList();
            holidays[entry.key] = list;
          }
        }
      } catch (e) {
        // ignore
      }

      // Populate defaults for leave fields in case they are missing
      for (var w in workers) {
        if (w['annualLeaves'] == null ||
            w['annualLeaves'].toString().trim().isEmpty) {
          w['annualLeaves'] = '12';
        }
        if (w['sickLeaves'] == null ||
            w['sickLeaves'].toString().trim().isEmpty) {
          w['sickLeaves'] = '8';
        }
        if (w['casualLeaves'] == null ||
            w['casualLeaves'].toString().trim().isEmpty) {
          w['casualLeaves'] = '10';
        }
        if (w['medicalLeaves'] == null ||
            w['medicalLeaves'].toString().trim().isEmpty) {
          w['medicalLeaves'] = '5';
        }
        if (w['leavesUsed'] == null ||
            w['leavesUsed'].toString().trim().isEmpty) {
          w['leavesUsed'] = '0';
        }
      }
    } catch (e) {
      // ignore
    }

    // Always persist the latest source data so that new fields
    // (e.g. status, payrollDate) are picked up after app updates.
    await saveToPrefs();
  }

  static Future<void> saveToPrefs() async {
    try {
      final prefs = await SharedPreferences.getInstance();
      await prefs.setString('dummy_workers', jsonEncode(workers));
      await prefs.setString('dummy_expenses', jsonEncode(expenses));
      await prefs.setString('dummy_attendance', jsonEncode(attendance));
      await prefs.setString('dummy_payroll', jsonEncode(payroll));
      await prefs.setString('dummy_timeoff', jsonEncode(timeoff));
      await prefs.setString('dummy_assets', jsonEncode(assets));
      await prefs.setString('dummy_holidays', jsonEncode(holidays));
    } catch (_) {
      // Ignore save errors
    }
  }

  static final List<Map<String, dynamic>> workers = [
    {
      'id': 'dummy_1',
      'name': 'John Smith',
      'email': 'john.smith@stark.com',
      'phone': '+1 555-0101',
      'gender': 'Male',
      'fatherName': 'William Smith',
      'joiningDate': 'January 15, 2022',
      'salaryAmount': '95,000',
      'currency': 'USD',
      'type1': 'Full-Time',
      'position': 'Senior Web Developer',
      'type2': 'Remote',
      'annualLeaves': '12',
      'sickLeaves': '8',
      'casualLeaves': '10',
      'medicalLeaves': '5',
      'leavesUsed': '0',
      'profileImage': 'assets/imageplaceholder.png',
      'nationalId': '35202-1234567-1',
      'experienceLevel': 'Senior',
      'education': 'BS Computer Science',
      'salaryType': 'Monthly',
      'religion': 'Christianity',
      'dob': 'March 12, 1990',
      'relationshipStatus': 'Married',
      'address': '123 Tech Street, Silicon Valley, CA',
    },
    {
      'id': 'dummy_2',
      'name': 'Michael Johnson',
      'email': 'michael.johnson@stark.com',
      'phone': '+1 555-0102',
      'gender': 'Male',
      'fatherName': 'Robert Johnson',
      'joiningDate': 'March 10, 2022',
      'salaryAmount': '75,000',
      'currency': 'USD',
      'type1': 'Full-Time',
      'position': 'UI/UX Designer',
      'type2': 'On-Site',
      'annualLeaves': '12',
      'sickLeaves': '8',
      'casualLeaves': '10',
      'medicalLeaves': '5',
      'leavesUsed': '0',
      'profileImage': 'assets/boy.png',
      'nationalId': '35202-2345678-2',
      'experienceLevel': 'Mid-Level',
      'education': 'BFA Design',
      'salaryType': 'Monthly',
      'religion': 'Christianity',
      'dob': 'July 8, 1992',
      'relationshipStatus': 'Single',
      'address': '456 Design Ave, New York, NY',
    },
    {
      'id': 'dummy_3',
      'name': 'Robert Wilson',
      'email': 'robert.wilson@stark.com',
      'phone': '+1 555-0103',
      'gender': 'Male',
      'fatherName': 'James Wilson',
      'joiningDate': 'June 20, 2023',
      'salaryAmount': '85,000',
      'currency': 'USD',
      'type1': 'Contract',
      'position': 'DevOps Engineer',
      'type2': 'On-Site',
      'annualLeaves': '12',
      'sickLeaves': '8',
      'casualLeaves': '10',
      'medicalLeaves': '5',
      'leavesUsed': '0',
      'profileImage': 'assets/imageplaceholder.png',
      'nationalId': '35202-3456789-3',
      'experienceLevel': 'Senior',
      'education': 'MS Information Technology',
      'salaryType': 'Monthly',
      'religion': 'Islam',
      'dob': 'November 22, 1988',
      'relationshipStatus': 'Married',
      'address': '789 Cloud Lane, Seattle, WA',
    },
    {
      'id': 'dummy_4',
      'name': 'Emily Davis',
      'email': 'emily.davis@stark.com',
      'phone': '+1 555-0104',
      'gender': 'Female',
      'fatherName': 'Richard Davis',
      'joiningDate': 'February 5, 2021',
      'salaryAmount': '110,000',
      'currency': 'USD',
      'type1': 'Full-Time',
      'position': 'Product Manager',
      'type2': 'On-Site',
      'annualLeaves': '12',
      'sickLeaves': '8',
      'casualLeaves': '10',
      'medicalLeaves': '5',
      'leavesUsed': '0',
      'profileImage': 'assets/boy.png',
      'nationalId': '35202-4567890-4',
      'experienceLevel': 'Lead',
      'education': 'MBA Business',
      'salaryType': 'Monthly',
      'religion': 'Christianity',
      'dob': 'April 15, 1987',
      'relationshipStatus': 'Married',
      'address': '321 Product Blvd, Austin, TX',
    },
    {
      'id': 'dummy_5',
      'name': 'David Brown',
      'email': 'david.brown@stark.com',
      'phone': '+1 555-0105',
      'gender': 'Male',
      'fatherName': 'Thomas Brown',
      'joiningDate': 'August 12, 2022',
      'salaryAmount': '65,000',
      'currency': 'USD',
      'type1': 'Part-Time',
      'position': 'Marketing Specialist',
      'type2': 'Remote',
      'annualLeaves': '12',
      'sickLeaves': '8',
      'casualLeaves': '10',
      'medicalLeaves': '5',
      'leavesUsed': '0',
      'profileImage': 'assets/imageplaceholder.png',
      'nationalId': '35202-5678901-5',
      'experienceLevel': 'Mid-Level',
      'education': 'BA Marketing',
      'salaryType': 'Monthly',
      'religion': 'Judaism',
      'dob': 'September 30, 1993',
      'relationshipStatus': 'Single',
      'address': '555 Market Street, San Francisco, CA',
    },
    {
      'id': 'dummy_6',
      'name': 'James Miller',
      'email': 'james.miller@stark.com',
      'phone': '+1 555-0106',
      'gender': 'Male',
      'fatherName': 'Charles Miller',
      'joiningDate': 'November 3, 2022',
      'salaryAmount': '90,000',
      'currency': 'USD',
      'type1': 'Full-Time',
      'position': 'Backend Engineer',
      'type2': 'Remote',
      'annualLeaves': '12',
      'sickLeaves': '8',
      'casualLeaves': '10',
      'medicalLeaves': '5',
      'leavesUsed': '0',
      'profileImage': 'assets/boy.png',
      'nationalId': '35202-6789012-6',
      'experienceLevel': 'Senior',
      'education': 'BS Software Engineering',
      'salaryType': 'Monthly',
      'religion': 'Buddhism',
      'dob': 'January 5, 1989',
      'relationshipStatus': 'Married',
      'address': '888 Backend Rd, Portland, OR',
    },
    {
      'id': 'dummy_7',
      'name': 'Sophia Martinez',
      'email': 'sophia.martinez@stark.com',
      'phone': '+1 555-0107',
      'gender': 'Female',
      'fatherName': 'Carlos Martinez',
      'joiningDate': 'April 18, 2021',
      'salaryAmount': '80,000',
      'currency': 'USD',
      'type1': 'Full-Time',
      'position': 'HR Manager',
      'type2': 'On-Site',
      'annualLeaves': '12',
      'sickLeaves': '8',
      'casualLeaves': '10',
      'medicalLeaves': '5',
      'leavesUsed': '0',
      'profileImage': 'assets/imageplaceholder.png',
      'nationalId': '35202-7890123-7',
      'experienceLevel': 'Senior',
      'education': 'MBA Human Resources',
      'salaryType': 'Monthly',
      'religion': 'Christianity',
      'dob': 'June 18, 1986',
      'relationshipStatus': 'Married',
      'address': '222 HR Park, Denver, CO',
    },
    {
      'id': 'dummy_8',
      'name': 'Daniel Anderson',
      'email': 'daniel.anderson@stark.com',
      'phone': '+1 555-0108',
      'gender': 'Male',
      'fatherName': 'Mark Anderson',
      'joiningDate': 'September 25, 2023',
      'salaryAmount': '70,000',
      'currency': 'USD',
      'type1': 'Contract',
      'position': 'Frontend Developer',
      'type2': 'Remote',
      'annualLeaves': '12',
      'sickLeaves': '8',
      'casualLeaves': '10',
      'medicalLeaves': '5',
      'leavesUsed': '0',
      'profileImage': 'assets/boy.png',
      'nationalId': '35202-8901234-8',
      'experienceLevel': 'Mid-Level',
      'education': 'BS Computer Science',
      'salaryType': 'Monthly',
      'religion': 'Hinduism',
      'dob': 'December 1, 1991',
      'relationshipStatus': 'Single',
      'address': '444 Frontend Way, Chicago, IL',
    },
    {
      'id': 'dummy_9',
      'name': 'Olivia Thomas',
      'email': 'olivia.thomas@stark.com',
      'phone': '+1 555-0109',
      'gender': 'Female',
      'fatherName': 'Steven Thomas',
      'joiningDate': 'July 8, 2022',
      'salaryAmount': '60,000',
      'currency': 'USD',
      'type1': 'Full-Time',
      'position': 'QA Engineer',
      'type2': 'On-Site',
      'annualLeaves': '12',
      'sickLeaves': '8',
      'casualLeaves': '10',
      'medicalLeaves': '5',
      'leavesUsed': '0',
      'profileImage': 'assets/imageplaceholder.png',
      'nationalId': '35202-9012345-9',
      'experienceLevel': 'Junior',
      'education': 'BS Quality Assurance',
      'salaryType': 'Monthly',
      'religion': 'Sikhism',
      'dob': 'February 14, 1995',
      'relationshipStatus': 'Single',
      'address': '777 QA Drive, Boston, MA',
    },
    {
      'id': 'dummy_10',
      'name': 'Lucas Taylor',
      'email': 'lucas.taylor@stark.com',
      'phone': '+1 555-0110',
      'gender': 'Male',
      'fatherName': 'Paul Taylor',
      'joiningDate': 'May 14, 2021',
      'salaryAmount': '105,000',
      'currency': 'USD',
      'type1': 'Full-Time',
      'position': 'Solutions Architect',
      'type2': 'On-Site',
      'annualLeaves': '12',
      'sickLeaves': '8',
      'casualLeaves': '10',
      'medicalLeaves': '5',
      'leavesUsed': '0',
      'profileImage': 'assets/boy.png',
      'nationalId': '35202-0123456-0',
      'experienceLevel': 'Lead',
      'education': 'MS Computer Science',
      'salaryType': 'Monthly',
      'religion': 'Christianity',
      'dob': 'October 8, 1985',
      'relationshipStatus': 'Married',
      'address': '101 Architect Lane, Miami, FL',
    },
    {
      'id': 'dummy_11',
      'name': 'Amelia White',
      'email': 'amelia.white@stark.com',
      'phone': '+1 555-0111',
      'gender': 'Female',
      'fatherName': 'George White',
      'joiningDate': 'October 22, 2023',
      'salaryAmount': '55,000',
      'currency': 'USD',
      'type1': 'Part-Time',
      'position': 'Graphic Designer',
      'type2': 'Remote',
      'annualLeaves': '12',
      'sickLeaves': '8',
      'casualLeaves': '10',
      'medicalLeaves': '5',
      'leavesUsed': '0',
      'profileImage': 'assets/imageplaceholder.png',
      'nationalId': '35202-1122334-1',
      'experienceLevel': 'Junior',
      'education': 'BFA Graphic Design',
      'salaryType': 'Monthly',
      'religion': 'Islam',
      'dob': 'May 20, 1996',
      'relationshipStatus': 'Single',
      'address': '333 Creative Blvd, Los Angeles, CA',
    },
    {
      'id': 'dummy_12',
      'name': 'Benjamin Harris',
      'email': 'benjamin.harris@stark.com',
      'phone': '+1 555-0112',
      'gender': 'Male',
      'fatherName': 'Edward Harris',
      'joiningDate': 'December 1, 2022',
      'salaryAmount': '88,000',
      'currency': 'USD',
      'type1': 'Full-Time',
      'position': 'Mobile Developer',
      'type2': 'Remote',
      'annualLeaves': '12',
      'sickLeaves': '8',
      'casualLeaves': '10',
      'medicalLeaves': '5',
      'leavesUsed': '0',
      'profileImage': 'assets/boy.png',
      'nationalId': '35202-2233445-2',
      'experienceLevel': 'Senior',
      'education': 'BS Mobile Computing',
      'salaryType': 'Monthly',
      'religion': 'Christianity',
      'dob': 'August 3, 1990',
      'relationshipStatus': 'Married',
      'address': '666 Mobile Park, Dallas, TX',
    },
    {
      'id': 'dummy_13',
      'name': 'Charlotte Martin',
      'email': 'charlotte.martin@stark.com',
      'phone': '+1 555-0113',
      'gender': 'Female',
      'fatherName': 'Henry Martin',
      'joiningDate': 'March 30, 2023',
      'nationalId': '35202-3344556-3',
      'experienceLevel': 'Mid-Level',
      'education': 'BS Business Administration',
      'salaryType': 'Monthly',
      'religion': 'Hinduism',
      'dob': 'November 11, 1993',
      'relationshipStatus': 'Single',
      'address': '999 Business Center, Phoenix, AZ',
      'salaryAmount': '92,000',
      'currency': 'USD',
      'type1': 'Full-Time',
      'position': 'Cyber Security Analyst',
      'type2': 'On-Site',
      'annualLeaves': '12',
      'sickLeaves': '8',
      'casualLeaves': '10',
      'medicalLeaves': '5',
      'leavesUsed': '0',
      'profileImage': 'assets/imageplaceholder.png',
    },
    {
      'id': 'dummy_14',
      'name': 'Henry Thompson',
      'email': 'henry.thompson@stark.com',
      'phone': '+1 555-0114',
      'gender': 'Male',
      'fatherName': 'Frank Thompson',
      'joiningDate': 'January 5, 2024',
      'salaryAmount': '98,000',
      'currency': 'USD',
      'type1': 'Contract',
      'position': 'Data Scientist',
      'type2': 'Remote',
      'annualLeaves': '12',
      'sickLeaves': '8',
      'casualLeaves': '10',
      'medicalLeaves': '5',
      'leavesUsed': '0',
      'profileImage': 'assets/boy.png',
      'nationalId': '35202-4455667-4',
      'experienceLevel': 'Senior',
      'education': 'PhD Data Science',
      'salaryType': 'Monthly',
      'religion': 'Christianity',
      'dob': 'March 25, 1987',
      'relationshipStatus': 'Married',
      'address': '159 Data Drive, San Jose, CA',
    },
    {
      'id': 'dummy_15',
      'name': 'Harper Garcia',
      'email': 'harper.garcia@stark.com',
      'phone': '+1 555-0115',
      'gender': 'Female',
      'fatherName': 'Miguel Garcia',
      'joiningDate': 'July 19, 2023',
      'salaryAmount': '58,000',
      'currency': 'USD',
      'type1': 'Part-Time',
      'position': 'Technical Writer',
      'type2': 'Remote',
      'annualLeaves': '12',
      'sickLeaves': '8',
      'casualLeaves': '10',
      'medicalLeaves': '5',
      'leavesUsed': '0',
      'profileImage': 'assets/imageplaceholder.png',
      'nationalId': '35202-5566778-5',
      'experienceLevel': 'Junior',
      'education': 'BA English Literature',
      'salaryType': 'Monthly',
      'religion': 'Buddhism',
      'dob': 'July 7, 1997',
      'relationshipStatus': 'Single',
      'address': '753 Writer Lane, Seattle, WA',
    },
  ];

  static final List<Map<String, dynamic>> expenses = [
    {
      'id': 'dummy_e1',
      'name': 'Client Dinner with Acme Corp',
      'date': '05/01/2026',
      'category': 'Meals',
      'amount': 124.50,
      'profileImage': 'assets/imageplaceholder.png',
    },
    {
      'id': 'dummy_e2',
      'name': 'Figma Team Subscription',
      'date': '10/01/2026',
      'category': 'Software',
      'amount': 45.00,
      'profileImage': 'assets/boy.png',
    },
    {
      'id': 'dummy_e3',
      'name': 'Wireless Mechanical Keyboard',
      'date': '15/02/2026',
      'category': 'Equipment',
      'amount': 89.99,
      'profileImage': 'assets/imageplaceholder.png',
    },
    {
      'id': 'dummy_e4',
      'name': 'AWS Cloud Hosting - Feb',
      'date': '01/02/2026',
      'category': 'Infrastructure',
      'amount': 250.00,
      'profileImage': 'assets/boy.png',
    },
    {
      'id': 'dummy_e5',
      'name': 'Google Ads - Spring Campaign',
      'date': '20/03/2026',
      'category': 'Marketing',
      'amount': 500.00,
      'profileImage': 'assets/imageplaceholder.png',
    },
    {
      'id': 'dummy_e6',
      'name': 'GitHub Enterprise License',
      'date': '12/03/2026',
      'category': 'Software',
      'amount': 150.00,
      'profileImage': 'assets/boy.png',
    },
    {
      'id': 'dummy_e7',
      'name': 'Recruiting Software - Q1',
      'date': '22/03/2026',
      'category': 'Software',
      'amount': 320.00,
      'profileImage': 'assets/imageplaceholder.png',
    },
    {
      'id': 'dummy_e8',
      'name': 'Remote Work Internet Allowance',
      'date': '19/04/2026',
      'category': 'Utilities',
      'amount': 60.00,
      'profileImage': 'assets/boy.png',
    },
    {
      'id': 'dummy_e9',
      'name': 'QA Testing Device - Pixel Tablet',
      'date': '15/04/2026',
      'category': 'Equipment',
      'amount': 299.00,
      'profileImage': 'assets/imageplaceholder.png',
    },
    {
      'id': 'dummy_e10',
      'name': 'Ergonomic Office Chair',
      'date': '10/05/2026',
      'category': 'Furniture',
      'amount': 180.00,
      'profileImage': 'assets/boy.png',
    },
    {
      'id': 'dummy_e11',
      'name': 'Adobe Creative Cloud - Annual',
      'date': '08/05/2026',
      'category': 'Software',
      'amount': 79.99,
      'profileImage': 'assets/imageplaceholder.png',
    },
    {
      'id': 'dummy_e12',
      'name': 'Tech Conference 2026 Tickets',
      'date': '05/05/2026',
      'category': 'Events',
      'amount': 400.00,
      'profileImage': 'assets/boy.png',
    },
    {
      'id': 'dummy_e13',
      'name': 'Apple Developer Program Renewal',
      'date': '06/06/2026',
      'category': 'Software',
      'amount': 99.00,
      'profileImage': 'assets/imageplaceholder.png',
    },
    {
      'id': 'dummy_e14',
      'name': 'YubiKey Security Keys - Team',
      'date': '05/06/2026',
      'category': 'Security',
      'amount': 55.00,
      'profileImage': 'assets/boy.png',
    },
    {
      'id': 'dummy_e15',
      'name': 'DataCamp Team Subscription',
      'date': '03/06/2026',
      'category': 'Training',
      'amount': 150.00,
      'profileImage': 'assets/imageplaceholder.png',
    },
    {
      'id': 'dummy_e16',
      'name': 'Team Lunch - Q2 Review',
      'date': '07/07/2026',
      'category': 'Meals',
      'amount': 210.00,
      'profileImage': 'assets/boy.png',
    },
    {
      'id': 'dummy_e17',
      'name': 'JetBrains All Products Pack',
      'date': '15/07/2026',
      'category': 'Software',
      'amount': 350.00,
      'profileImage': 'assets/imageplaceholder.png',
    },
    {
      'id': 'dummy_e18',
      'name': 'Client Visit - Flight & Hotel',
      'date': '20/08/2026',
      'category': 'Travel',
      'amount': 475.00,
      'profileImage': 'assets/boy.png',
    },
    {
      'id': 'dummy_e19',
      'name': 'Office Supplies - Printer Ink',
      'date': '10/08/2026',
      'category': 'Supplies',
      'amount': 65.00,
      'profileImage': 'assets/imageplaceholder.png',
    },
    {
      'id': 'dummy_e20',
      'name': 'Client Meeting - Downtown',
      'date': '05/09/2026',
      'category': 'Travel',
      'amount': 180.00,
      'profileImage': 'assets/boy.png',
    },
    {
      'id': 'dummy_e21',
      'name': 'Hotel Booking - Partner Summit',
      'date': '12/09/2026',
      'category': 'Travel',
      'amount': 520.00,
      'profileImage': 'assets/imageplaceholder.png',
    },
    {
      'id': 'dummy_e22',
      'name': 'Office Internet Bill - Oct',
      'date': '13/10/2026',
      'category': 'Utilities',
      'amount': 45.00,
      'profileImage': 'assets/boy.png',
    },
    {
      'id': 'dummy_e23',
      'name': 'Client Dinner - Product Demo',
      'date': '20/10/2026',
      'category': 'Meals',
      'amount': 290.00,
      'profileImage': 'assets/imageplaceholder.png',
    },
    {
      'id': 'dummy_e24',
      'name': 'Social Media Marketing Campaign',
      'date': '15/11/2026',
      'category': 'Marketing',
      'amount': 750.00,
      'profileImage': 'assets/boy.png',
    },
    {
      'id': 'dummy_e25',
      'name': 'Flight Tickets - Tech Conference',
      'date': '16/12/2026',
      'category': 'Travel',
      'amount': 890.00,
      'profileImage': 'assets/imageplaceholder.png',
    },
  ];

  static final List<Map<String, dynamic>> attendance = [
    {
      'id': 'dummy_a1',
      'name': 'John Smith',
      'email': 'john.smith@stark.com',
      'role': 'Senior Web Developer',
      'status': 'Present',
      'attendanceType': 'Remote',
      'workType': 'Full Time',
      'profileImage': 'assets/imageplaceholder.png',
    },
    {
      'id': 'dummy_a2',
      'name': 'Michael Johnson',
      'email': 'michael.johnson@stark.com',
      'role': 'UI/UX Designer',
      'status': 'Present',
      'attendanceType': 'On-Site',
      'workType': 'Full Time',
      'profileImage': 'assets/imageplaceholder.png',
    },
    {
      'id': 'dummy_a3',
      'name': 'Robert Wilson',
      'email': 'robert.wilson@stark.com',
      'role': 'DevOps Engineer',
      'status': 'Absent',
      'attendanceType': 'On-Site',
      'workType': 'Contract',
      'profileImage': 'assets/imageplaceholder.png',
    },
    {
      'id': 'dummy_a4',
      'name': 'Emily Davis',
      'email': 'emily.davis@stark.com',
      'role': 'Product Manager',
      'status': 'Present',
      'attendanceType': 'On-Site',
      'workType': 'Full Time',
      'profileImage': 'assets/imageplaceholder.png',
    },
    {
      'id': 'dummy_a5',
      'name': 'David Brown',
      'email': 'david.brown@stark.com',
      'role': 'Marketing Specialist',
      'status': 'Leave',
      'type': 'Casual Leave',
      'attendanceType': 'Remote',
      'workType': 'Part Time',
      'profileImage': 'assets/imageplaceholder.png',
    },
    {
      'id': 'dummy_a6',
      'name': 'James Miller',
      'email': 'james.miller@stark.com',
      'role': 'Backend Engineer',
      'status': 'Present',
      'attendanceType': 'Remote',
      'workType': 'Full Time',
      'profileImage': 'assets/imageplaceholder.png',
    },
    {
      'id': 'dummy_a7',
      'name': 'Sophia Martinez',
      'email': 'sophia.martinez@stark.com',
      'role': 'HR Manager',
      'status': 'Present',
      'attendanceType': 'On-Site',
      'workType': 'Full Time',
      'profileImage': 'assets/imageplaceholder.png',
    },
    {
      'id': 'dummy_a8',
      'name': 'Daniel Anderson',
      'email': 'daniel.anderson@stark.com',
      'role': 'Frontend Developer',
      'status': 'Present',
      'attendanceType': 'Remote',
      'workType': 'Contract',
      'profileImage': 'assets/imageplaceholder.png',
    },
    {
      'id': 'dummy_a9',
      'name': 'Olivia Thomas',
      'email': 'olivia.thomas@stark.com',
      'role': 'QA Engineer',
      'status': 'Present',
      'attendanceType': 'On-Site',
      'workType': 'Full Time',
      'profileImage': 'assets/imageplaceholder.png',
    },
    {
      'id': 'dummy_a10',
      'name': 'Lucas Taylor',
      'email': 'lucas.taylor@stark.com',
      'role': 'Solutions Architect',
      'status': 'Absent',
      'attendanceType': 'On-Site',
      'workType': 'Full Time',
      'profileImage': 'assets/imageplaceholder.png',
    },
    {
      'id': 'dummy_a11',
      'name': 'Amelia White',
      'email': 'amelia.white@stark.com',
      'role': 'Graphic Designer',
      'status': 'Leave',
      'attendanceType': 'Remote',
      'workType': 'Part Time',
      'type': 'Sick Leave',
      'desc': 'Sick leave due to fever, doctor advised rest for 2 days.',
      'profileImage': 'assets/imageplaceholder.png',
    },
    {
      'id': 'dummy_a12',
      'name': 'Benjamin Harris',
      'email': 'benjamin.harris@stark.com',
      'role': 'Mobile Developer',
      'status': 'Present',
      'attendanceType': 'Remote',
      'workType': 'Full Time',
      'profileImage': 'assets/imageplaceholder.png',
    },
    {
      'id': 'dummy_a13',
      'name': 'Charlotte Martin',
      'email': 'charlotte.martin@stark.com',
      'role': 'Cyber Security Analyst',
      'status': 'Present',
      'attendanceType': 'On-Site',
      'workType': 'Full Time',
      'profileImage': 'assets/imageplaceholder.png',
    },
    {
      'id': 'dummy_a14',
      'name': 'Henry Thompson',
      'email': 'henry.thompson@stark.com',
      'role': 'Data Scientist',
      'status': 'Leave',
      'type': 'Medical Leave',
      'attendanceType': 'Remote',
      'workType': 'Contract',
      'desc':
          'Medical leave for surgery recovery, doctor recommended 1 week rest.',
      'profileImage': 'assets/imageplaceholder.png',
    },
    {
      'id': 'dummy_a15',
      'name': 'Harper Garcia',
      'email': 'harper.garcia@stark.com',
      'role': 'Technical Writer',
      'status': 'Leave',
      'type': 'Medical Leave',
      'attendanceType': 'Remote',
      'workType': 'Part Time',
      'desc': 'Medical leave for dental surgery, doctor advised 3 days rest.',
      'profileImage': 'assets/imageplaceholder.png',
    },
  ];

  static final List<Map<String, dynamic>> payroll = [
    {
      'id': 'dummy_p1',
      'name': 'John Smith',
      'email': 'john.smith@stark.com',
      'position': 'Senior Web Developer',
      'contact': '+1 555-0101',
      'status': 'Paid',
      'totalWorkDays': '240',
      'absents': '04',
      'leaves': '08',
      'overtimeDays': '12',
      'overtimeAmount': '\$ 0',
      'absentDeduction': '\$ 0',
      'leaveDeduction': '\$ 0',
      'netSalary': '\$ 95,000',
      'salary': '\$ 95,000',
      'profileImage': 'assets/imageplaceholder.png',
      'payrollDate': '15/07/2026',
    },
    {
      'id': 'dummy_p2',
      'name': 'Michael Johnson',
      'email': 'michael.johnson@stark.com',
      'position': 'UI/UX Designer',
      'contact': '+1 555-0102',
      'status': 'Paid',
      'totalWorkDays': '230',
      'absents': '02',
      'leaves': '06',
      'overtimeDays': '05',
      'overtimeAmount': '\$ 0',
      'absentDeduction': '\$ 0',
      'leaveDeduction': '\$ 0',
      'netSalary': '\$ 75,000',
      'salary': '\$ 75,000',
      'profileImage': 'assets/boy.png',
      'payrollDate': '15/07/2026',
    },
    {
      'id': 'dummy_p3',
      'name': 'Robert Wilson',
      'email': 'robert.wilson@stark.com',
      'position': 'DevOps Engineer',
      'contact': '+1 555-0103',
      'status': 'Paid',
      'totalWorkDays': '120',
      'absents': '01',
      'leaves': '02',
      'overtimeDays': '00',
      'overtimeAmount': '\$ 0',
      'absentDeduction': '\$ 0',
      'leaveDeduction': '\$ 0',
      'netSalary': '\$ 85,000',
      'salary': '\$ 85,000',
      'profileImage': 'assets/imageplaceholder.png',
      'payrollDate': '15/07/2026',
    },
    {
      'id': 'dummy_p4',
      'name': 'Emily Davis',
      'email': 'emily.davis@stark.com',
      'position': 'Product Manager',
      'contact': '+1 555-0104',
      'status': 'Paid',
      'totalWorkDays': '250',
      'absents': '01',
      'leaves': '10',
      'overtimeDays': '15',
      'overtimeAmount': '\$ 0',
      'absentDeduction': '\$ 0',
      'leaveDeduction': '\$ 0',
      'netSalary': '\$ 110,000',
      'salary': '\$ 110,000',
      'profileImage': 'assets/boy.png',
      'payrollDate': '15/07/2026',
    },
    {
      'id': 'dummy_p5',
      'name': 'David Brown',
      'email': 'david.brown@stark.com',
      'position': 'Marketing Specialist',
      'contact': '+1 555-0105',
      'status': 'Unpaid',
      'totalWorkDays': '180',
      'absents': '05',
      'leaves': '12',
      'overtimeDays': '02',
      'overtimeAmount': '\$ 0',
      'absentDeduction': '\$ 0',
      'leaveDeduction': '\$ 0',
      'netSalary': '\$ 60,000',
      'salary': '\$ 60,000',
      'profileImage': 'assets/imageplaceholder.png',
      'payrollDate': '15/07/2026',
    },
    {
      'id': 'dummy_p6',
      'name': 'James Miller',
      'email': 'james.miller@stark.com',
      'position': 'Backend Engineer',
      'contact': '+1 555-0106',
      'status': 'Unpaid',
      'totalWorkDays': '220',
      'absents': '03',
      'leaves': '05',
      'overtimeDays': '08',
      'overtimeAmount': '\$ 0',
      'absentDeduction': '\$ 0',
      'leaveDeduction': '\$ 0',
      'netSalary': '\$ 80,000',
      'salary': '\$ 80,000',
      'profileImage': 'assets/boy.png',
      'payrollDate': '15/07/2026',
    },
    {
      'id': 'dummy_p7',
      'name': 'Sophia Martinez',
      'email': 'sophia.martinez@stark.com',
      'position': 'HR Manager',
      'contact': '+1 555-0107',
      'status': 'Unpaid',
      'totalWorkDays': '240',
      'absents': '00',
      'leaves': '04',
      'overtimeDays': '02',
      'overtimeAmount': '\$ 0',
      'absentDeduction': '\$ 0',
      'leaveDeduction': '\$ 0',
      'netSalary': '\$ 70,000',
      'salary': '\$ 70,000',
      'profileImage': 'assets/imageplaceholder.png',
      'payrollDate': '15/07/2026',
    },
    {
      'id': 'dummy_p8',
      'name': 'Daniel Anderson',
      'email': 'daniel.anderson@stark.com',
      'position': 'Frontend Developer',
      'contact': '+1 555-0108',
      'status': 'Unpaid',
      'totalWorkDays': '150',
      'absents': '02',
      'leaves': '03',
      'overtimeDays': '04',
      'overtimeAmount': '\$ 0',
      'absentDeduction': '\$ 0',
      'leaveDeduction': '\$ 0',
      'netSalary': '\$ 65,000',
      'salary': '\$ 65,000',
      'profileImage': 'assets/boy.png',
      'payrollDate': '15/07/2026',
    },
    {
      'id': 'dummy_p9',
      'name': 'Olivia Thomas',
      'email': 'olivia.thomas@stark.com',
      'position': 'QA Engineer',
      'contact': '+1 555-0109',
      'status': 'Unpaid',
      'totalWorkDays': '245',
      'absents': '01',
      'leaves': '05',
      'overtimeDays': '06',
      'overtimeAmount': '\$ 0',
      'absentDeduction': '\$ 0',
      'leaveDeduction': '\$ 0',
      'netSalary': '\$ 68,000',
      'salary': '\$ 68,000',
      'profileImage': 'assets/imageplaceholder.png',
      'payrollDate': '15/07/2026',
    },
    {
      'id': 'dummy_p10',
      'name': 'Lucas Taylor',
      'email': 'lucas.taylor@stark.com',
      'position': 'Solutions Architect',
      'contact': '+1 555-0110',
      'status': 'Unpaid',
      'totalWorkDays': '210',
      'absents': '04',
      'leaves': '08',
      'overtimeDays': '10',
      'overtimeAmount': '\$ 0',
      'absentDeduction': '\$ 0',
      'leaveDeduction': '\$ 0',
      'netSalary': '\$ 120,000',
      'salary': '\$ 120,000',
      'profileImage': 'assets/boy.png',
      'payrollDate': '15/07/2026',
    },
    {
      'id': 'dummy_p11',
      'name': 'Amelia White',
      'email': 'amelia.white@stark.com',
      'position': 'Graphic Designer',
      'contact': '+1 555-0111',
      'status': 'Unpaid',
      'totalWorkDays': '160',
      'absents': '03',
      'leaves': '15',
      'overtimeDays': '01',
      'overtimeAmount': '\$ 0',
      'absentDeduction': '\$ 0',
      'leaveDeduction': '\$ 0',
      'netSalary': '\$ 55,000',
      'salary': '\$ 55,000',
      'profileImage': 'assets/imageplaceholder.png',
      'payrollDate': '15/07/2026',
    },
    {
      'id': 'dummy_p12',
      'name': 'Benjamin Harris',
      'email': 'benjamin.harris@stark.com',
      'position': 'Mobile Developer',
      'contact': '+1 555-0112',
      'status': 'Unpaid',
      'totalWorkDays': '220',
      'absents': '02',
      'leaves': '05',
      'overtimeDays': '10',
      'overtimeAmount': '\$ 0',
      'absentDeduction': '\$ 0',
      'leaveDeduction': '\$ 0',
      'netSalary': '\$ 88,000',
      'salary': '\$ 88,000',
      'profileImage': 'assets/boy.png',
      'payrollDate': '15/07/2026',
    },
    {
      'id': 'dummy_p13',
      'name': 'Charlotte Martin',
      'email': 'charlotte.martin@stark.com',
      'position': 'Cyber Security Analyst',
      'contact': '+1 555-0113',
      'status': 'Unpaid',
      'totalWorkDays': '240',
      'absents': '01',
      'leaves': '04',
      'overtimeDays': '02',
      'overtimeAmount': '\$ 0',
      'absentDeduction': '\$ 0',
      'leaveDeduction': '\$ 0',
      'netSalary': '\$ 90,000',
      'salary': '\$ 90,000',
      'profileImage': 'assets/imageplaceholder.png',
      'payrollDate': '15/07/2026',
    },
    {
      'id': 'dummy_p14',
      'name': 'Henry Thompson',
      'email': 'henry.thompson@stark.com',
      'position': 'Data Scientist',
      'contact': '+1 555-0114',
      'status': 'Unpaid',
      'totalWorkDays': '125',
      'absents': '01',
      'leaves': '03',
      'overtimeDays': '00',
      'overtimeAmount': '\$ 0',
      'absentDeduction': '\$ 0',
      'leaveDeduction': '\$ 0',
      'netSalary': '\$ 95,000',
      'salary': '\$ 95,000',
      'profileImage': 'assets/boy.png',
      'payrollDate': '15/07/2026',
    },
    {
      'id': 'dummy_p15',
      'name': 'Harper Garcia',
      'email': 'harper.garcia@stark.com',
      'position': 'Technical Writer',
      'contact': '+1 555-0115',
      'status': 'Unpaid',
      'totalWorkDays': '150',
      'absents': '03',
      'leaves': '12',
      'overtimeDays': '01',
      'overtimeAmount': '\$ 0',
      'absentDeduction': '\$ 0',
      'leaveDeduction': '\$ 0',
      'netSalary': '\$ 48,000',
      'salary': '\$ 48,000',
      'profileImage': 'assets/imageplaceholder.png',
      'payrollDate': '15/07/2026',
    },
  ];

  static final List<Map<String, dynamic>> timeoff = [
    {
      'id': 'dummy_t1',
      'name': 'John Smith',
      'email': 'john.smith@stark.com',
      'position': 'Senior Web Developer',
      'contact': '+1 555-0101',
      'action': 'Annual Leave',
      'startDate': '2026-07-10',
      'endDate': '2026-07-15',
      'requestedDays': 5,
      'profileImage': 'assets/imageplaceholder.png',
    },
    {
      'id': 'dummy_t2',
      'name': 'Michael Johnson',
      'email': 'michael.johnson@stark.com',
      'position': 'UI/UX Designer',
      'contact': '+1 555-0102',
      'action': 'Sick Leave',
      'startDate': '2026-07-12',
      'endDate': '2026-07-13',
      'requestedDays': 2,
      'profileImage': 'assets/boy.png',
    },
    {
      'id': 'dummy_t3',
      'name': 'Robert Wilson',
      'email': 'robert.wilson@stark.com',
      'position': 'DevOps Engineer',
      'contact': '+1 555-0103',
      'action': 'Casual Leave',
      'startDate': '2026-07-08',
      'endDate': '2026-07-09',
      'requestedDays': 2,
      'profileImage': 'assets/imageplaceholder.png',
    },
    {
      'id': 'dummy_t4',
      'name': 'David Brown',
      'email': 'david.brown@stark.com',
      'position': 'Marketing Specialist',
      'contact': '+1 555-0105',
      'action': 'Maternity Leave',
      'startDate': '2026-06-20',
      'endDate': '2026-07-20',
      'requestedDays': 30,
      'profileImage': 'assets/boy.png',
    },
    {
      'id': 'dummy_t5',
      'name': 'James Miller',
      'email': 'james.miller@stark.com',
      'position': 'Backend Engineer',
      'contact': '+1 555-0106',
      'action': 'Annual Leave',
      'startDate': '2026-07-11',
      'endDate': '2026-07-14',
      'requestedDays': 3,
      'profileImage': 'assets/imageplaceholder.png',
    },
    {
      'id': 'dummy_t6',
      'name': 'Sophia Martinez',
      'email': 'sophia.martinez@stark.com',
      'position': 'HR Manager',
      'contact': '+1 555-0107',
      'action': 'Sick Leave',
      'startDate': '2026-07-13',
      'endDate': '2026-07-13',
      'requestedDays': 1,
      'profileImage': 'assets/boy.png',
    },
    {
      'id': 'dummy_t7',
      'name': 'Daniel Anderson',
      'email': 'daniel.anderson@stark.com',
      'position': 'Frontend Developer',
      'contact': '+1 555-0108',
      'action': 'Casual Leave',
      'startDate': '2026-07-07',
      'endDate': '2026-07-08',
      'requestedDays': 2,
      'profileImage': 'assets/imageplaceholder.png',
    },
    {
      'id': 'dummy_t8',
      'name': 'Olivia Thomas',
      'email': 'olivia.thomas@stark.com',
      'position': 'QA Engineer',
      'contact': '+1 555-0109',
      'action': 'Maternity Leave',
      'startDate': '2026-06-01',
      'endDate': '2026-07-01',
      'requestedDays': 30,
      'profileImage': 'assets/boy.png',
    },
    {
      'id': 'dummy_t9',
      'name': 'Lucas Taylor',
      'email': 'lucas.taylor@stark.com',
      'position': 'Solutions Architect',
      'contact': '+1 555-0110',
      'action': 'Annual Leave',
      'startDate': '2026-07-09',
      'endDate': '2026-07-12',
      'requestedDays': 3,
      'profileImage': 'assets/imageplaceholder.png',
    },
    {
      'id': 'dummy_t10',
      'name': 'Amelia White',
      'email': 'amelia.white@stark.com',
      'position': 'Graphic Designer',
      'contact': '+1 555-0111',
      'action': 'Sick Leave',
      'startDate': '2026-07-06',
      'endDate': '2026-07-07',
      'requestedDays': 2,
      'profileImage': 'assets/boy.png',
    },
    {
      'id': 'dummy_t11',
      'name': 'Benjamin Harris',
      'email': 'benjamin.harris@stark.com',
      'position': 'Mobile Developer',
      'contact': '+1 555-0112',
      'action': 'Annual Leave',
      'startDate': '2026-07-01',
      'endDate': '2026-07-05',
      'requestedDays': 5,
      'profileImage': 'assets/imageplaceholder.png',
    },
    {
      'id': 'dummy_t12',
      'name': 'Charlotte Martin',
      'email': 'charlotte.martin@stark.com',
      'position': 'Cyber Security Analyst',
      'contact': '+1 555-0113',
      'action': 'Sick Leave',
      'startDate': '2026-07-10',
      'endDate': '2026-07-11',
      'requestedDays': 2,
      'profileImage': 'assets/boy.png',
    },
    {
      'id': 'dummy_t13',
      'name': 'Henry Thompson',
      'email': 'henry.thompson@stark.com',
      'position': 'Data Scientist',
      'contact': '+1 555-0114',
      'action': 'Medical Leave',
      'startDate': '2026-07-14',
      'endDate': '2026-07-18',
      'requestedDays': 5,
      'profileImage': 'assets/imageplaceholder.png',
    },
    {
      'id': 'dummy_t14',
      'name': 'Sarah Connor',
      'email': 'sarah.connor@stark.com',
      'position': 'Project Manager',
      'contact': '+1 555-0115',
      'action': 'Custom Leave',
      'startDate': '2026-07-20',
      'endDate': '2026-07-22',
      'requestedDays': 3,
      'profileImage': 'assets/imageplaceholder.png',
    },
    {
      'id': 'dummy_t15',
      'name': 'Mike Peters',
      'email': 'mike.peters@stark.com',
      'position': 'Software Engineer',
      'contact': '+1 555-0116',
      'action': 'Annual Leave',
      'startDate': '2026-07-25',
      'endDate': '2026-07-29',
      'requestedDays': 5,
      'profileImage': 'assets/boy.png',
    },
    {
      'id': 'dummy_t16',
      'name': 'Laura Palmer',
      'email': 'laura.palmer@stark.com',
      'position': 'Business Analyst',
      'contact': '+1 555-0117',
      'action': 'Sick Leave',
      'startDate': '2026-07-18',
      'endDate': '2026-07-19',
      'requestedDays': 2,
      'profileImage': 'assets/imageplaceholder.png',
    },
  ];

  static final Map<String, List<Map<String, dynamic>>> holidays = {
    'May': [
      {
        'day': 1,
        'month': 'May',
        'remainingDays': '05',
        'dayOfWeek': 'Saturday',
        'name': 'Labour Day',
        'isEnabled': true,
      },
      {
        'day': 3,
        'month': 'May',
        'remainingDays': '07',
        'dayOfWeek': 'Monday',
        'name': 'Eid-ul-Fitr Holiday',
        'isEnabled': true,
      },
      {
        'day': 6,
        'month': 'May',
        'remainingDays': '10',
        'dayOfWeek': 'Thursday',
        'name': 'Memorial Day',
        'isEnabled': true,
      },
      {
        'day': 10,
        'month': 'May',
        'remainingDays': '14',
        'dayOfWeek': 'Monday',
        'name': 'Eid-ul-Adha Holiday',
        'isEnabled': true,
      },
      {
        'day': 14,
        'month': 'May',
        'remainingDays': '18',
        'dayOfWeek': 'Sunday',
        'name': 'Mother\'s Day',
        'isEnabled': true,
      },
      {
        'day': 15,
        'month': 'May',
        'remainingDays': '19',
        'dayOfWeek': 'Monday',
        'name': 'Independence Day',
        'isEnabled': true,
      },
      {
        'day': 18,
        'month': 'May',
        'remainingDays': '22',
        'dayOfWeek': 'Thursday',
        'name': 'Founder\'s Day',
        'isEnabled': true,
      },
      {
        'day': 20,
        'month': 'May',
        'remainingDays': '24',
        'dayOfWeek': 'Saturday',
        'name': 'Spring Break',
        'isEnabled': true,
      },
      {
        'day': 22,
        'month': 'May',
        'remainingDays': '26',
        'dayOfWeek': 'Monday',
        'name': 'Youth Day',
        'isEnabled': true,
      },
      {
        'day': 25,
        'month': 'May',
        'remainingDays': '29',
        'dayOfWeek': 'Thursday',
        'name': 'National Day',
        'isEnabled': true,
      },
      {
        'day': 26,
        'month': 'May',
        'remainingDays': '30',
        'dayOfWeek': 'Friday',
        'name': 'Victoria Day',
        'isEnabled': true,
      },
      {
        'day': 28,
        'month': 'May',
        'remainingDays': '32',
        'dayOfWeek': 'Sunday',
        'name': 'Bank Holiday',
        'isEnabled': true,
      },
      {
        'day': 29,
        'month': 'May',
        'remainingDays': '33',
        'dayOfWeek': 'Monday',
        'name': 'Ascension Day',
        'isEnabled': true,
      },
      {
        'day': 30,
        'month': 'May',
        'remainingDays': '34',
        'dayOfWeek': 'Tuesday',
        'name': 'Unity Day',
        'isEnabled': true,
      },
      {
        'day': 31,
        'month': 'May',
        'remainingDays': '35',
        'dayOfWeek': 'Wednesday',
        'name': 'Memorial Feast',
        'isEnabled': true,
      },
    ],
    'Feb': [
      {
        'day': 1,
        'month': 'Feb',
        'remainingDays': '02',
        'dayOfWeek': 'Wednesday',
        'name': 'Groundhog Day',
        'isEnabled': true,
      },
      {
        'day': 6,
        'month': 'Feb',
        'remainingDays': '07',
        'dayOfWeek': 'Monday',
        'name': 'Super Bowl',
        'isEnabled': true,
      },
      {
        'day': 14,
        'month': 'Feb',
        'remainingDays': '15',
        'dayOfWeek': 'Tuesday',
        'name': 'Valentine\'s Day',
        'isEnabled': true,
      },
      {
        'day': 26,
        'month': 'Feb',
        'remainingDays': '27',
        'dayOfWeek': 'Monday',
        'name': 'Presidents\' Day',
        'isEnabled': true,
      },
    ],
    'Jun': [
      {
        'day': 5,
        'month': 'Jun',
        'remainingDays': '05',
        'dayOfWeek': 'Thursday',
        'name': 'Eid-ul-Adha',
        'isEnabled': true,
      },
      {
        'day': 14,
        'month': 'Jun',
        'remainingDays': '14',
        'dayOfWeek': 'Saturday',
        'name': 'Flag Day',
        'isEnabled': true,
      },
      {
        'day': 19,
        'month': 'Jun',
        'remainingDays': '19',
        'dayOfWeek': 'Thursday',
        'name': 'Juneteenth',
        'isEnabled': true,
      },
      {
        'day': 21,
        'month': 'Jun',
        'remainingDays': '21',
        'dayOfWeek': 'Saturday',
        'name': 'Summer Solstice',
        'isEnabled': true,
      },
      {
        'day': 30,
        'month': 'Jun',
        'remainingDays': '30',
        'dayOfWeek': 'Monday',
        'name': 'Mid-Year Break',
        'isEnabled': true,
      },
    ],
    'Jul': [
      {
        'day': 4,
        'month': 'Jul',
        'remainingDays': '04',
        'dayOfWeek': 'Friday',
        'name': 'Independence Day',
        'isEnabled': true,
      },
      {
        'day': 12,
        'month': 'Jul',
        'remainingDays': '12',
        'dayOfWeek': 'Saturday',
        'name': 'Summer Festival',
        'isEnabled': true,
      },
      {
        'day': 20,
        'month': 'Jul',
        'remainingDays': '20',
        'dayOfWeek': 'Sunday',
        'name': 'National Ice Cream Day',
        'isEnabled': true,
      },
      {
        'day': 28,
        'month': 'Jul',
        'remainingDays': '28',
        'dayOfWeek': 'Monday',
        'name': 'Company Retreat',
        'isEnabled': true,
      },
    ],
  };

  static final List<Map<String, dynamic>> notifications = [
    {
      'id': 'dummy_n1',
      'type': 'welcome',
      'title': 'notif_title_welcome'.tr(namedArgs: {'name': 'to HRMS'}),
      'message': 'notif_msg_welcome'.tr(),
      'data': {'name': 'to HRMS'},
      'isRead': false,
      'createdAt': DateTime.now()
          .subtract(const Duration(minutes: 5))
          .toIso8601String(),
    },
    {
      'id': 'dummy_n2',
      'type': 'attendance_marked',
      'title': 'notif_title_attendance'.tr(namedArgs: {'name': '15 employees'}),
      'message': 'notif_msg_attendance'.tr(namedArgs: {'name': '15 employees'}),
      'data': {'name': '15 employees'},
      'isRead': false,
      'createdAt': DateTime.now()
          .subtract(const Duration(hours: 2))
          .toIso8601String(),
    },
    {
      'id': 'dummy_n3',
      'type': 'time_off_added',
      'title': 'notif_title_time_off'.tr(
        namedArgs: {'name': 'Michael Johnson'},
      ),
      'message': 'notif_msg_time_off'.tr(
        namedArgs: {'type': 'Sick Leave', 'name': 'Michael Johnson'},
      ),
      'data': {'type': 'Sick Leave', 'name': 'Michael Johnson'},
      'isRead': false,
      'createdAt': DateTime.now()
          .subtract(const Duration(hours: 5))
          .toIso8601String(),
    },
    {
      'id': 'dummy_n4',
      'type': 'payroll_added',
      'title': 'notif_title_payroll'.tr(namedArgs: {'name': 'June 2026'}),
      'message': 'notif_msg_payroll'.tr(namedArgs: {'name': 'June 2026'}),
      'data': {'name': 'June 2026'},
      'isRead': true,
      'createdAt': DateTime.now()
          .subtract(const Duration(days: 1))
          .toIso8601String(),
    },
    {
      'id': 'dummy_n5',
      'type': 'holiday_added',
      'title': 'notif_title_holiday'.tr(
        namedArgs: {'name': 'Independence Day'},
      ),
      'message': 'notif_msg_holiday'.tr(
        namedArgs: {'name': 'Independence Day'},
      ),
      'data': {'name': 'Independence Day'},
      'isRead': true,
      'createdAt': DateTime.now()
          .subtract(const Duration(days: 2))
          .toIso8601String(),
    },
    {
      'id': 'dummy_n6',
      'type': 'expense_added',
      'title': 'notif_title_expense'.tr(),
      'message': 'notif_msg_expense_amount'.tr(
        namedArgs: {'amount': '\$475.00'},
      ),
      'data': {'amount': '\$475.00', 'category': ''},
      'isRead': false,
      'createdAt': DateTime.now()
          .subtract(const Duration(hours: 8))
          .toIso8601String(),
    },
    {
      'id': 'dummy_n7',
      'type': 'expense_added',
      'title': 'notif_title_expense'.tr(),
      'message': 'notif_msg_expense_amount'.tr(
        namedArgs: {'amount': '\$124.50'},
      ),
      'data': {'amount': '\$124.50', 'category': ''},
      'isRead': true,
      'createdAt': DateTime.now()
          .subtract(const Duration(days: 3))
          .toIso8601String(),
    },
    {
      'id': 'dummy_n8',
      'type': 'asset_added',
      'title': 'notif_title_asset_type'.tr(namedArgs: {'type': 'MacBook Pro'}),
      'message': 'notif_msg_asset_type'.tr(
        namedArgs: {'type': 'MacBook Pro', 'name': 'Sophia Martinez'},
      ),
      'data': {'type': 'MacBook Pro', 'name': 'Sophia Martinez'},
      'isRead': true,
      'createdAt': DateTime.now()
          .subtract(const Duration(days: 4))
          .toIso8601String(),
    },
  ];

  static final List<Map<String, dynamic>> assets = [
    {
      'name': 'Emily Davis',
      'position': 'Product Manager',
      'type': 'Laptop',
      'dateLoaned': '15/01/2025',
      'dateReturned': '15/01/2025',
      'isReturned': true,
      'profileImage': 'assets/imageplaceholder.png',
    },
    {
      'name': 'Amelia White',
      'position': 'Graphic Designer',
      'type': 'Mouse',
      'dateLoaned': '10/03/2025',
      'dateReturned': 'in_use',
      'isReturned': false,
      'profileImage': 'assets/boy.png',
    },
    {
      'name': 'Charlotte Martin',
      'position': 'Cyber Security Analyst',
      'type': 'Keyboard',
      'dateLoaned': '20/05/2025',
      'dateReturned': '20/05/2025',
      'isReturned': true,
      'profileImage': 'assets/imageplaceholder.png',
    },
    {
      'name': 'Sophia Martinez',
      'position': 'HR Manager',
      'type': 'Mac',
      'dateLoaned': '05/02/2025',
      'dateReturned': 'in_use',
      'isReturned': false,
      'profileImage': 'assets/boy.png',
    },
    {
      'name': 'Daniel Anderson',
      'position': 'Frontend Developer',
      'type': 'Table',
      'dateLoaned': '12/04/2025',
      'dateReturned': 'in_use',
      'isReturned': false,
      'profileImage': 'assets/imageplaceholder.png',
    },
    {
      'name': 'John Smith',
      'position': 'Backend Developer',
      'type': 'Monitor',
      'dateLoaned': '18/06/2025',
      'dateReturned': 'in_use',
      'isReturned': false,
      'profileImage': 'assets/boy.png',
    },
    {
      'name': 'Michael Johnson',
      'position': 'DevOps Engineer',
      'type': 'Headphone',
      'dateLoaned': '22/06/2025',
      'dateReturned': '22/06/2025',
      'isReturned': true,
      'profileImage': 'assets/imageplaceholder.png',
    },
    {
      'name': 'Olivia Thomas',
      'position': 'UI Designer',
      'type': 'iPad',
      'dateLoaned': '01/07/2025',
      'dateReturned': 'in_use',
      'isReturned': false,
      'profileImage': 'assets/boy.png',
    },
    {
      'name': 'James Miller',
      'position': 'Backend Engineer',
      'type': 'Laptop',
      'dateLoaned': '05/07/2025',
      'dateReturned': '05/07/2025',
      'isReturned': true,
      'profileImage': 'assets/imageplaceholder.png',
    },
    {
      'name': 'Harper Garcia',
      'position': 'Technical Writer',
      'type': 'Keyboard',
      'dateLoaned': '10/08/2025',
      'dateReturned': 'in_use',
      'isReturned': false,
      'profileImage': 'assets/boy.png',
    },
    {
      'name': 'Benjamin Harris',
      'position': 'Mobile Developer',
      'type': 'iPhone',
      'dateLoaned': '15/08/2025',
      'dateReturned': 'in_use',
      'isReturned': false,
      'profileImage': 'assets/imageplaceholder.png',
    },
    {
      'name': 'Lucas Taylor',
      'position': 'Solutions Architect',
      'type': 'Monitor',
      'dateLoaned': '20/09/2025',
      'dateReturned': '20/09/2025',
      'isReturned': true,
      'profileImage': 'assets/boy.png',
    },
  ];
}
