// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf4NJ9TcuRKpMDO75xltm-gl847rSpAgU',
    appId: '1:806894781275:web:71e0d39eadb34dc50dd07e',
    messagingSenderId: '806894781275',
    projectId: 'myauthapp-5cc2c',
    authDomain: 'myauthapp-5cc2c.firebaseapp.com',
    storageBucket: 'myauthapp-5cc2c.firebasestorage.app',
    measurementId: 'G-NX9VHX2SKC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvn_5NjkzUGu80d8SQoxkjbtq2ncre0CY',
    appId: '1:806894781275:android:abd8a89c96a053f10dd07e',
    messagingSenderId: '806894781275',
    projectId: 'myauthapp-5cc2c',
    storageBucket: 'myauthapp-5cc2c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGZ1nIhhoEyBOi7HZ5AeKTFw5tcPA4rgg',
    appId: '1:806894781275:ios:6afbeeaa8cfbe82e0dd07e',
    messagingSenderId: '806894781275',
    projectId: 'myauthapp-5cc2c',
    storageBucket: 'myauthapp-5cc2c.firebasestorage.app',
    iosClientId: '806894781275-5lat5a7h4vejedjkc0uka65h1ne17338.apps.googleusercontent.com',
    iosBundleId: 'com.example.hrms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGZ1nIhhoEyBOi7HZ5AeKTFw5tcPA4rgg',
    appId: '1:806894781275:ios:6afbeeaa8cfbe82e0dd07e',
    messagingSenderId: '806894781275',
    projectId: 'myauthapp-5cc2c',
    storageBucket: 'myauthapp-5cc2c.firebasestorage.app',
    iosClientId: '806894781275-5lat5a7h4vejedjkc0uka65h1ne17338.apps.googleusercontent.com',
    iosBundleId: 'com.example.hrms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBf4NJ9TcuRKpMDO75xltm-gl847rSpAgU',
    appId: '1:806894781275:web:4ea223de9104fb660dd07e',
    messagingSenderId: '806894781275',
    projectId: 'myauthapp-5cc2c',
    authDomain: 'myauthapp-5cc2c.firebaseapp.com',
    storageBucket: 'myauthapp-5cc2c.firebasestorage.app',
    measurementId: 'G-1P4VNM8P7S',
  );

}